### ISSUE TITLE
usual ctrl+ functionality disabled in conversations

### ISSUE THREAD

**Issue by schmitz-michi** [thunderbird-conversations/thunderbird-conversations#1585] opened 2021-01-11 18:45 UTC
* **Thunderbird version: 78.6.0 (32-Bit)**
* **Thunderbird Conversation version: 3.2.11**
* **Operating System: Windows 10**

**What did you do?**
In Thunderbird without the Conversations addon when reading mails I liked to use the shortcuts ctrl+ and ctrl- to adjust the font size. When the Conversations addon is activated these shortcuts adjust the size of the symbols and so on. Is there a way to adjust the font size in the familiar flexible way?

**Comment by Standard8** [comment] 2021-03-06 15:04
I'm going to dupe this forward to #1600 since that is a slightly better/clearer description

**Comment by Standard8** [comment] 2021-03-06 15:04
Duplicate of #1600

**Closed by Standard8** 2021-03-06 15:04 UTC
Labels: bug
