### ISSUE TITLE
Conflicts with Header Tool Lite 2.0.2

### ISSUE THREAD

**Issue by ht618** [thunderbird-conversations/thunderbird-conversations#2134] opened 2024-08-23 04:31 UTC
* **Thunderbird version: 115.10.1**
* **Thunderbird Conversation version: 4.1.7**
* **Operating System: Windows 11 23H2**

**What did you do?**
Thunderbird Conversation installed in an environment with Header Tool Lite 2.0.2 installed.
**What did you expect to happen?**

**What actually happened?**
Header Tools Lite 2.0.2 is no opetation available after installing Thunderbird Conversation; it works by disabling Thunderbird Conversations.

**Comment by jandoemen** [comment] 2024-09-08 07:56
Same with other versions

- Thunderbird version: 128.2.0esr (64-bit)
- Thunderbird Conversation version: 4.2.1
- Operating System: Windows 10

What did you do?
- Installed "Header Tools Improved 4.8" => works fine
- Installed "Thunderbird Conversation 4.2.1" installed => Header tool doesn't work anymore

What did you expect to happen?
That "Header Tools Improved 4.8" would still work.

What actually happened?
"Header Tools Improved 4.8" doesn't show the popup forms it should do.
When deactivating "Thunderbird Conversations", "Header Tools Improved 4.8" works again.

**Comment by Standard8** [comment] 2024-09-08 08:36
The main problem here is that Header Tools Improved (I assume it is the same for the Lite version), assumes that the message pane only ever displays a single message. You can see that you get the same issue with Conversations disabled if you select multiple messages (either in a thread or a multiple selection) and attempt to change the headers using Header Tools Improved.

It can also be seen that Header Tools Improved has a bug in relying on what's displayed on the message pane. If I right-click on a non-selected message in the message list and choose to edit the headers, then it shows me the headers for the message loaded in the message pane, not the message I actually selected.

Due to the way Conversations works, you're always in a multiple message view, as you're potentially seeing messages from other threads as well. Hence the Header Tools don't work as they don't know how to handle this.

From the Conversations' perspective, there's not much I can do here, Conversations needs the multiple message view to work, and it is setting up the views according to that - hence as far as I'm concerned it is operating correctly in this space.

I think this is really up to the authors of the Header Tools add-ons. They have the option to know only what is selected in the message list versus what is displayed in the message pane, and they should be able to manage to change headers of messages that aren't directly loaded in the message pane.

Hence I'm closing this out, as this is a compatibility/functionality issue caused by the Header Tools add-ons, not by Conversations.

**Closed by Standard8** 2024-09-08 08:36 UTC
Labels: add-on compat

**Comment by ht618** [comment] 2024-09-09 01:18
Thanks for your kind reply, I will contact the developer of The Header Tools add-ons.
