### ISSUE TITLE
Feature request: Selecting text and clicking reply should open the compose window with only the selected text shown

### ISSUE THREAD

**Issue by Piiit** [thunderbird-conversations/thunderbird-conversations#1555] opened 2020-11-12 10:09 UTC
Feature request:
Selecting text and clicking reply, does normally remove all other text before opening the compose window with only the selected text present (and if configured the signature at the end). 

Please add a possiblity to send the selected text only to the compose window.

Thank you for this great addon! 

Cheers,
Peter

**Comment by Standard8** [comment] 2020-11-16 21:21
Duplicate of #174

**Closed by Standard8** 2020-11-16 21:21 UTC
