### ISSUE TITLE
Merges messages from two different subjects together

### ISSUE THREAD

**Issue by snowbound** [thunderbird-conversations/thunderbird-conversations#1564] opened 2020-11-27 19:21 UTC
* **Thunderbird version:**78.5.0 (64-bit
* **Thunderbird Conversation version:**3.2.7
* **Operating System:**Windows10 2004

**What did you do?**
I clicked on the subject of a particular message. 

**What did you expect to happen?**
Only show the initial message and replies to that message whose subject is what I clicked on.

**What actually happened?**
It displays the body of two messages and replies to those two messages 

No idea if this more detailed explanation will help or whether it will confuse you https://support.mozilla.org/en-US/questions/1315631#answer-1371025

I am using these settings 

![image](https://user-images.githubusercontent.com/596147/100479433-d1ad3200-30b3-11eb-8d9d-8bcf4886dfd8.png)

**Comment by Standard8** [comment] 2020-11-29 11:16
Could you provide a screenshot of the issue? It is slightly unclear from the sumo report exactly what the issue is.

Feel free to blank out parts if necessary.

It might also be useful to turn on Debugging (at the bottom of the settings), restart and then open up the error console (under Tools -> Developer Tools) and get a lot of what happens when you click one of the broken messages.

**Comment by snowbound** [comment] 2020-11-29 16:27
I did that but do not know what in the Debugger you want.  Here is the issue. The message at the top is regarding a UPS and the bottom portion is a conversation I had with someone else re iron capsules. This issue is always involving the correspondent regarding the UPS. In other words I have several emails back and forth with the subject "Ups for this system" and every one of those messages winds up showing an email for another subject with another person.

![2020-11-29_101847](https://user-images.githubusercontent.com/596147/100547475-94b87b00-322c-11eb-9064-cc8ad5a65c45.jpg)
![2020-11-29_101447](https://user-images.githubusercontent.com/596147/100547559-fb3d9900-322c-11eb-85e6-ea74af0075d5.jpg)

**Comment by snowbound** [comment] 2020-11-29 16:30
I did that but do not know what in the Debugger you want. Here is the issue. The message at the top is regarding a UPS and the bottom portion is a conversation I had with someone else re iron capsules. This issue is always involving the correspondent regarding the UPS. In other words I have several emails back and forth with the subject "Ups for this system" and every one of those messages winds up showing an email for another subject with another person. I have blanked out my email address as those for the recepients in the screen capture and debugging.

![2020-11-29_101447](https://user-images.githubusercontent.com/596147/100547721-dd246880-322d-11eb-8b00-cc1052535e6e.jpg)
![2020-11-29_101847](https://user-images.githubusercontent.com/596147/100547723-df86c280-322d-11eb-95d2-66e33d7352c3.jpg)

**Comment by agustusbotti** [comment] 2020-12-09 12:25
Hello, I also have the same problem.
I leave you a capture of what happens to me, as you will see the emails are from 2019 and the last one is from today in 2020. It happens to me with many emails

![image](https://user-images.githubusercontent.com/70614796/101629681-7c9ce480-3a00-11eb-9270-c7b69ea1873a.png)

**Comment by snowbound** [comment] 2020-12-09 14:39
Thank you Marcelo for posting that confirmation example. Was the subject of
those two groups of emails two completely different subjects?

**Comment by agustusbotti** [comment] 2020-12-09 19:48
Correct, totally different and with one year of difference between them.

**Comment by snowbound** [comment] 2020-12-09 19:55
I just checked and seen the behaviour here involving a thread from this
past weekend and one recipient which also erroneously showed a single email
I sent to someone else whose message subject was nothing to do with the
threaded message.

**Comment by Standard8** [comment] 2020-12-13 14:03
Here's something you could try:

- Select one of the messages
- In the three-dots at the right of the message header in conversations, select "view using the classic reader"
- On the classic reader display, select the more button at the end of the header, and select "Open In Conversation"

If the messages there are incorrectly grouped, then this is an issue with Thunderbird's handling of conversation threading, rather than Conversations itself.

**Comment by snowbound** [comment] 2020-12-13 15:27
I went back to the initial message that I saw this happening and it is also
happening in Classic reader as wel.

**Comment by Standard8** [comment] 2020-12-13 18:01
Thanks for the filing that, I'll leave this open for a few days but will probably close it soon as it isn't Conversations specific.

**Comment by Standard8** [comment] 2020-12-29 08:17
Looking at the suport issue, rebuilding the global database fixed it - i.e. it was a Thunderbird issue.

Hence, closing this report.

**Closed by Standard8** 2020-12-29 08:17 UTC
Labels: thunderbird issue
