### ISSUE TITLE
Read email in Conversations is not read in main window

### ISSUE THREAD

**Issue by pH142857** [thunderbird-conversations/thunderbird-conversations#1539] opened 2020-10-09 15:26 UTC
* **Thunderbird version:** 68.10.0 (64 bits)
* **Thunderbird Conversation version:** 3.1.24
* **Operating System:** Ubuntu

**What did you do?**
In the main tab, I open the first message of a conversation composed of two unread emails. In the Conversations tab, I read the first message, then I scroll down to the second one and read it as well.
**What did you expect to happen?**
In the main tab, the second one should appear read, as I read it.
**What actually happened?**
The second message appears unread until I double-click on it to open the same Conversations tab again.

**Comment by Standard8** [comment] 2020-10-16 20:22
Did you scroll all the way to the bottom of the second message? Conversations only marks it as read once you get to the bottom.

**Comment by pH142857** [comment] 2020-10-26 16:42
Looks like it actually works when scrolling all the way. Funny how I never noticed it.

**Comment by pH142857** [comment] 2020-11-25 17:27
Re-opening this because I'm eventually really experiencing the bug. The steps are :
**1) Receive an answer to an email you wrote and open the already read email**
![conversation1](https://user-images.githubusercontent.com/11050141/100260709-0a30fc80-2f4a-11eb-9617-16dcee23a77b.png)
![conversation2](https://user-images.githubusercontent.com/11050141/100260711-0ac99300-2f4a-11eb-8090-bcb2fdf84027.png)
What happens here is that the conversation according to TB Conversations isn't the same as the conversation according to Thunderbird. I had a 4 mail-conversation with my correspondent, which TB Conversations displays well, but for Thunderbird it's just a 2 mail-thread with only my correspondent's answers included. So **we might have a deep modelling problem here**. Is anyone aware of that? Should it be reported to TB tickets?
2) In the Conversations panel, open the last email and be sure to scroll all the way down.
![conversation4](https://user-images.githubusercontent.com/11050141/100260716-0b622980-2f4a-11eb-9b5f-d5c98a5434c6.png)
The email is still unread in the main panel.
**3) The workaround: open the mail in between (the one __you__ sent)**
![conversation3](https://user-images.githubusercontent.com/11050141/100260714-0ac99300-2f4a-11eb-8db9-f35390ea79b8.png)
The last mail finally appears as read in the main panel.

**Comment by Standard8** [comment] 2020-11-29 13:06
If you're sending an email to yourself, then Conversations will see the email be added to the sent box, before it gets received by you. So it will add the sent email to the conversation. When you then receive the email, it will ignore it as it sees it as a duplicate, so scrolling to the end won't mark it as read, as the sent email is already read.

It is possible we could somehow keep track of the duplicates, and mark both as read (if not already), but that'd be quite a bit of work, and I don't see this as a "normal" use case, so it would be low priority to fix.

**Comment by pH142857** [comment] 2020-12-07 17:49
I am not sending an email to myself, I am using another address which is not connected to my Thunderbird.

**Comment by Standard8** [comment] 2020-12-13 19:39
Unfortunately I can't reproduce this, and I can't see how the scroll detection would be affected by having the second to last item expanded or not.

The only thing I can suggest trying is to update to the latest Thunderbird (78) and the latest Conversations, if you haven't already.

**Comment by Standard8** [comment] 2021-01-31 21:44
Given we've not had any more reports for this, I'm going to close it out. If it is still occurring in the latest Thunderbird & Conversation builds please feel free to comment or file a new issue.

**Closed by Standard8** 2021-01-31 21:44 UTC
