### ISSUE TITLE
Focus is on the "to" field instead of the text field when hitting "reply/reply all"

### ISSUE THREAD

**Issue by Slater91** [thunderbird-conversations/thunderbird-conversations#1754] opened 2021-11-17 13:47 UTC
* **Thunderbird version:** 91.3.0
* **Thunderbird Conversation version:** 4.0.5
* **Operating System:** Linux

**What did you do?**
I clicked on the "reply" and "reply all" buttons at the top of a message I received, so that a new window opens.

**What did you expect to happen?**
I expected the focus in the new window to be on the text field, so that I could type my reply right away. I can confirm that this is what happens when disabling Conversations.

**What actually happened?**
The focus was on the "to" field, as if I was typing a new message.

**Comment by Standard8** [comment] 2021-11-17 13:49
Duplicate of #1725

**Comment by Slater91** [comment] 2021-11-17 13:50
I looked for any open bug reports, but didn't find any. Thank you and sorry for the duplicate!

**Closed by Standard8** 2021-11-17 13:49 UTC

**Comment by Standard8** [comment] 2021-11-17 13:51
As I just commented there Thunderbird 93.3.1 has the fix (this was an issue in Thunderbird across multiple add-ons) - please update to the latest version when you can.
