### ISSUE TITLE
Reply not working after detaching an attachment

### ISSUE THREAD

**Issue by Buratinator** [thunderbird-conversations/thunderbird-conversations#1684] opened 2021-07-20 08:38 UTC
* **Thunderbird version:** 78.12.0 (32-bit)
* **Thunderbird Conversation version:** 3.2.26
* **Operating System:** Windows 10 Home x64 

**What did you do?**
Detached an attachment from an inbound message. Then clicked the Reply icon in the message header inside the Conversation view.

**What did you expect to happen?**
The Message Compose window should open

**What actually happened?**
Nothing

**Additional notes**
Replying from the main UI (right-click a message in the message list and selecting Reply to All) works as expected.

Until a few weeks ago, the message in the conversation view would go completely blank after detaching an attachment (probably related to https://github.com/thunderbird-conversations/thunderbird-conversations/issues/1496 ), so the only way to reply was to reload TB. Seems to be related to a recent TB update.

**Comment by Buratinator** [comment] 2021-07-29 06:27
Unfortunately, the issue persists, so not fixed.

**Comment by Buratinator** [comment] 2021-08-12 08:33
Updates:

1. The reply button worked if computer was put to sleep after detaching an attachment.

2. A change in behavior today (apparently after an update to the addon - now on version 3.2.33). Now, after detaching an attachment, the message goes blank again and TB behaves as if the message doesn't exist, which is the same behavior experienced earlier (as mentioned in my original report above where I said it was probably related to #1496 ).

**Comment by Standard8** [comment] 2021-08-13 11:06
Duplicate of #1496.

**Closed** 2021-08-13 11:06 UTC
