### ISSUE TITLE
Recipient names are split on comma

### ISSUE THREAD

**Issue by op3** [thunderbird-conversations/thunderbird-conversations#2051] opened 2023-11-22 09:40 UTC
* **Thunderbird version:** 115.4.2
* **Thunderbird Conversation version:** 4.1.5
* **Operating System:** Fedora 39

**What did you do?**

I received an e-mail with a recipient name containing a comma. The header looks like this:

```
To: "Lastname, Firstname" <firstname.lastname@example.com>
```

**What did you expect to happen?**

Thunderbird conversations should show a single recipient named “Lastname, Firstname \<firstname.lastname@example.com\>” (just like the classical Thunderbird reader).

**What actually happened?**

Thunderbird conversations showed two recipients “Lastname and Firstname \<firstname.lastname@example.com\>”. I can hover over each of them: For “Lastname”, a hover card for a person named “Lastname” is shown (no e-mail address), for “Firstname \<…\>”, a hover card for “Firstname” (with the e-mail address) is shown.

**Comment by Standard8** [comment] 2023-11-22 09:43
This is an issue with how Thunderbird is passing the names to the add-on.

Duplicate of #1927

**Closed by Standard8** 2023-11-22 09:43 UTC
