### ISSUE TITLE
Subject Lines in conversations

### ISSUE THREAD

**Issue by babalooza** [thunderbird-conversations/thunderbird-conversations#2128] opened 2024-07-31 19:52 UTC
* Thunderbird version: 128.0.1esr (but was the same in 115.x.x)
* Thunderbird Conversation version: 4.2.1
* Operating System: macOS Sonoma 14.5

**What did you do?**
I highlighted a conversation with multiple subject lines

**What did you expect to happen?**
Additionally to sender and recipients I expect to see the individual subject line on top of every email in the conversation

**What actually happened?**
On top of every email I just see the name of the sender and the names of the recipients. Only when I click the info or details button in the top right corner of an email I would see the individual subject line (next to the actual email addresses, the folder, date and time, and the user agent).

In telephone calls with members of an email conversation the subject line is often used to identify a specific email. But without seeing all subject lines in a conversation it is hard for me to find the email in question.

Thanks a lot for any help!

**Comment by Standard8** [comment] 2024-09-15 10:39
Duplicate of #2141 2141

**Closed by Standard8** 2024-09-15 10:39 UTC
