### ISSUE TITLE
When installed, then addon "Display Mail User Agent T" does not work

### ISSUE THREAD

**Issue by stratosjl** [thunderbird-conversations/thunderbird-conversations#1806] opened 2022-03-10 14:31 UTC
* **Thunderbird version:** 91.7.0 (64-bit)
* **Thunderbird Conversation version:** 4.0.12
* **Operating System:** Edition: Windows 10 Business / Version: 21H2 / Build: 19044.1586

**What did you do?** installed Thunderbird Conversations

**What did you expect to happen?** See icon with sending client identification at the top right of the email's reading pane, as is the task of plugin "Display Mail User Agent T"

**What actually happened?** The plugin "Display Mail User Agent T" is somehow blocked

**Comment by Standard8** [comment] 2022-03-18 09:51
Duplicate of #1609

**Comment by Standard8** [comment] 2022-03-18 09:53
As mentioned, this is known about already, unfortunately it is a hard case to support at the moment.

If the add-on used something like inserting a button into the toolbar rather than into the message itself, then that might be easier to get working in the shorter term.

**Closed by Standard8** 2022-03-18 09:53 UTC
