### ISSUE TITLE
Hyperlinks in mail body in popup conversation windows do not respond on click 

### ISSUE THREAD

**Issue by dryquart** [thunderbird-conversations/thunderbird-conversations#1774] opened 2022-01-12 12:19 UTC
* **Thunderbird version:** 91.4.1 (64-Bit) and 91.5.0 (64-Bit)
* **Thunderbird Conversation version:** 4.0.8
* **Operating System:** Windows 7 Prof., Build 7601, Service Pack 1

**What did you do?**
Clicked on any hyperlink displayed in the popup conversation window 

**What did you expect to happen?**
Browser is started (or gets focus if already open) and opens hyperlink

**What actually happened?**
Nothing. Mouse symbol changes correctly on mouse-over of the hyperlink, but the browser is not triggered upon clicking.
When the conversation is displayed in the Thunderbird Preview Pane, the hyperlinks respond on click.

**Debug output**
Switching to the popup conversations window throws this error:
> 13:15:15.607 Uncaught TypeError: window.browsingContext.topChromeWindow.contentAreaClick is not a function
>     clickIframe chrome://conversations/content/stub.bundle.js:900
>     createThunkMiddleware chrome://conversations/content/751.bundle.js:612
>     onClickIframe chrome://conversations/content/902.bundle.js:3975

Clicking on the hyperlink (displayed in HTML format as a button) throws this error:
> 13:16:18.964 Uncaught TypeError: window.arguments is undefined
>     loadRequestedUrl chrome://messenger/content/extensionPopup.js:47
>     onload chrome://messenger/content/extensionPopup.xhtml:1

**Comment by Standard8** [comment] 2022-01-12 12:24
Duplicate of #1766

**Comment by Standard8** [comment] 2022-01-12 12:25
This is fixed in 4.0.9 which is awaiting review by the addons.thunderbird.net team. Should hopefully be approved in the next day or so.

**Closed by Standard8** 2022-01-12 12:25 UTC
