### ISSUE TITLE
Cannot add a new contact from email with Thunderbird Conversations enabled.

### ISSUE THREAD

**Issue by micksulley** [thunderbird-conversations/thunderbird-conversations#1673] opened 2021-06-29 21:01 UTC
Without Thunderbird Conversations enabled I can right click on the sender email address and choose 'Add CardBook Contact'.  If I enable Conversations that option does not appear.  I raised this first as a CardBook issue in GitLab as issue #1291

* **Thunderbird version: 78.11.0 **
* **Thunderbird Conversation version:3.2.23**
* **Operating System: Linux Mint 20.1 Cinnamon**

**What did you do?  Right click to add contact to CardBook**

**What did you expect to happen? Add contact**

**What actually happened? The option is missing**

**Comment by Standard8** [comment] 2021-06-30 07:34
I've just realised this is a duplicate of #1193, please see my answer there.

**Closed by Standard8** 2021-06-30 07:34 UTC

**Comment by micksulley** [comment] 2021-06-30 08:43
Thanks for the reply Mark.  I have updated the issue in CardBook 
referencing your remarks.
