### ISSUE TITLE
Thunderbird update (78.4.0) Broke Conversations

### ISSUE THREAD

**Issue by e6lk7dqzm83p** [thunderbird-conversations/thunderbird-conversations#1554] opened 2020-11-10 02:26 UTC
* **Thunderbird version:**
78.4.0

* **Thunderbird Conversation version:**
3.2.6

* **Operating System:**
Debian

**What did you do?**
Auto update of Thunderbird to 78.4.0.  I've tried restarting Thunderbird, disabling/re-enabling Conversations, and setting up Conversations again (using the Setup Assistant)

**What did you expect to happen?**
No changes in performance

**What actually happened?*
When I click on messages the message area is blank, I can't see the message and it's unclear if the threading is working.

**Comment by Standard8** [comment] 2020-11-10 08:03
@e6lk7dqzm83p Please can you start Thunderbird, then go to the Three Bar Menu -> Tools -> Developer Tools -> Error Console, and see if any error messages are appearing on startup or when you select messages.

If there's nothing obvious, then if you go into Tools -> Add-ons -> Extensions, select the three dots next to Conversations and select preferences. At the bottom of that page turn on debugging. Then restart and open up the error console, and select an email again - in this case I'd like to see the entire log.

**Comment by e6lk7dqzm83p** [comment] 2020-11-10 15:24
Request to access cookie or storage on “https://addons.thunderbird.net/user-media/addon_icons/54/54035-64.png?modified=1598905689” was blocked because we are blocking all third-party storage access requests and content blocking is enabled.

2020-11-10 10:22:03.648	exquilla.base	INFO	Ews server starting Biff
2020-11-10 10:22:04.254	exquilla.base	WARN	mNumUnreadMessages not initialized
NS_ERROR_FAILURE: Malformed query 18 AddrBookManager.jsm:113
2020-11-10 10:23:05.104	exquilla.base	INFO	Ews server starting Biff
2020-11-10 10:23:05.584	exquilla.base	WARN	mNumUnreadMessages not initialized
NS_ERROR_FAILURE: Malformed query 27 AddrBookManager.jsm:113

​

**Comment by Standard8** [comment] 2020-11-10 16:00
Oh you're using Exquilla... this is already covered in #1536. It is their add-on causing the issue, I've contacted them and not heard anything back yet. Please feel free to do the same.

**Comment by Standard8** [comment] 2020-11-10 16:01
Duplicate of #1536

**Closed by Standard8** 2020-11-10 16:01 UTC

**Comment by e6lk7dqzm83p** [comment] 2020-11-10 16:09
Hi,

This happens with my non-exchange account (which is using IMAP).  Is that also being caused by Exquilla?

**Comment by e6lk7dqzm83p** [comment] 2020-11-10 16:13
It does seem to be Exquilla is causing an issue with IMAP as well.  Thanks for pointing me in the right direction!
