### ISSUE TITLE
Text for Sent button not seen 

### ISSUE THREAD

**Issue by Bruno-FGM** [thunderbird-conversations/thunderbird-conversations#2045] opened 2023-11-02 18:51 UTC
* **Thunderbird version:**
115.4.1
* **Thunderbird Conversation version:**
4.1.5
* **Operating System:**
Ubuntu 23.04

**What did you do?**
Answer mail and send 

**What did you expect to happen?**
See the sent text into the button

**What actually happened?**
no text is being seen 

![image](https://github.com/thunderbird-conversations/thunderbird-conversations/assets/97888863/0f1f8412-c0ae-4adc-bb7e-90c1a31cf49e)

**Comment by Standard8** [comment] 2023-11-04 09:37
Dupe of 1933

**Comment by Standard8** [comment] 2023-11-04 09:37
Duplicate of #1933

**Closed by Standard8** 2023-11-04 09:37 UTC
