### ISSUE TITLE
Ctrl+enter not working for sending message

### ISSUE THREAD

**Issue by joomlafun** [thunderbird-conversations/thunderbird-conversations#1854] opened 2022-06-08 08:39 UTC
Hi, 

This maybe a feature request and not an actual issue, sorry if I posted this in the wrong place. 

* **Thunderbird version:** 91.8.1
* **Thunderbird Conversation version:** 4.0.17
* **Operating System:** kubuntu 20.4

**What did you do?**
CTRL+entering when composing

**What did you expect to happen?**
Send the email

**What actually happened?**
Not sending the email

**Comment by Standard8** [comment] 2022-06-08 09:51
Duplicate of #1740

**Closed by Standard8** 2022-06-08 09:51 UTC
