### ISSUE TITLE
Problem with PGP encrypted titles

### ISSUE THREAD

**Issue by papiche** [thunderbird-conversations/thunderbird-conversations#2078] opened 2024-02-10 14:33 UTC
* **Thunderbird version:** 115.6.0 (64 bits)
* **Thunderbird Conversation version:** 4.1.6
* **Operating System:** 
```
NAME="Linux Mint"
VERSION="20.2 (Uma)"
ID=linuxmint
ID_LIKE=ubuntu
PRETTY_NAME="Linux Mint 20.2"
VERSION_ID="20.2"
HOME_URL="https://www.linuxmint.com/"
SUPPORT_URL="https://forums.linuxmint.com/"
BUG_REPORT_URL="http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/"
PRIVACY_POLICY_URL="https://www.linuxmint.com/"
VERSION_CODENAME=uma
UBUNTU_CODENAME=focal
```
**What did you do?**
Use end to end encryption

**What did you expect to happen?**
Title being decrypted 

**What actually happened?**
are replaced with RE: ...

**Comment by Standard8** [comment] 2024-02-24 13:14
Given that I still haven't got around to completing encryption support alongside 115 (its complicated & difficult), I'm not surprised this is broken. Marking as duplicate of #2006 which is the work to implement that.

**Closed by Standard8** 2024-02-24 13:14 UTC
