### ISSUE TITLE
After upgrade to 78.1: Hangs often for minutes

### ISSUE THREAD

**Issue by doits** [thunderbird-conversations/thunderbird-conversations#1519] opened 2020-08-05 08:03 UTC
* **Thunderbird version:** 78.1
* **Thunderbird Conversation version:** 3.1.19
* **Operating System:** MacOS 10.15.6

After upgrade to thunderbird 78.1, clicking on mails makes thunderbird hang. Sometimes it hangs multiple minutes. See the performance profile: https://share.firefox.dev/2Xv78sV

I cannot reproduce it with a specific action, opening different e-mails is enough though. Also it *seems* to hang longer if the thread has more messages or emails have some attachments, and sometimes hovering over the addresses of an e-mail (where it shows the popover with more details) makes it hang, too (but this could be a coincidence, too).

Disabling conversations addon resolves the issue completely.

This problem was not present in 68.x series of thunderbird. I'm unsure about 78.0 though or if it only started with 78.1 (don't remember if I upgraded straight to 78.1).

Is there anything I can do to provide more information?

**Comment by Standard8** [comment] 2020-08-05 09:14
That's definitely a bit strange and painful. I haven't seen anything like it on 78, but I also haven't been extensively using it yet. I'll try switching soon.

The profile is showing that garbage collection is taking place - this normally runs periodically to ensure any unused memory is cleaned up. However, that's a 57s hang which should obviously not be happening...

Like I say I'll take a look and I'll ask around a bit and see if there's anything we can do to diagnose this further.

**Comment by klapanciusz** [comment] 2020-08-07 17:34
I had to uninstall Conversations. Both with 78.0 and 78.1 it was hanging most of the time. At least 90% of the time, meaning that basically I couldn't use Thunderbird. Since I have uninstalled the Conversations, it wroks fine - but, of course, without the cool features that I am used to. Although I don't have a strict reproduction (as whatever I did very soon it was hanging), it seems that there were two things that particularly led to hanging: (1) arbitrary action + new mail arriving at the same time and (2) moving emails to different folders. I have traffic of 100-200 emails a day and about 60,000 emails stored (many with attachments). I do understand that this is a lot. But, perhaps that makes me a good test subject :-)

Another problem that may be related is that Conversations seems to do a different indexing than the Thunderbird normal indexing, and probably both try to happen at the same time. The result is that the threads are often wrong, these I usually fix using the 'repair folder' function - that will fix the mail list, however, I may get into a thread of 3 emails and find 50 emails listed there when I look inside the thread. These two, in addition to the missing quick reply, was certainly sufficient for me to uninstall the Conversations. The problem is that without the Conversations I am not sure that it is worth keeping Thunderbird. Outlook improved a lot in the last 10 years or so...

Best,
Viktor

**Comment by Standard8** [comment] 2020-08-07 20:31
> Another problem that may be related is that Conversations seems to do a different indexing than the Thunderbird normal indexing, and probably both try to happen at the same time. The result is that the threads are often wrong, these I usually fix using the 'repair folder' function - that will fix the mail list, however, I may get into a thread of 3 emails and find 50 emails listed there when I look inside the thread.

That is most likely a Thunderbird issue. I think if you try it without Conversations enabled, and select a message, and select "Open in conversation" - if that view is broken, then it is definitely a Thunderbird issue.

> The problem is that without the Conversations I am not sure that it is worth keeping Thunderbird. Outlook improved a lot in the last 10 years or so.

Please don't use threats. This is code that is all done in volunteer/spare time. This issue has only been raised recently, and seems to have got worse in 78 compared to 68. I have some ideas, but haven't had time to look in detail yet.

**Comment by klapanciusz** [comment] 2020-08-07 21:51
Thank you very much for your response - I am sorry, it was not anywhere on my mind to threaten. I know very well how much work many of you put in voluntarily. What I meant was that Conversations became such a crucial part of Thunderbird for me that I think it should be integrated into it. It is so very sensible what it does, how it works. The quick reply saved me many-many hours of work. So I was not rushing you, let alone threatening, I know that you took the Conversations over from Jonathan on the top of many other things you do, once he was not in the position to do it anymore, and I am extremely thankful for that.

I also meant to offer help testing. I am not a programmer, but I have quite a bit of experience testing, replicating problems, and such. So, if there is something that I should test, please, let me know.

Regarding the 'merging the threads' in the message view, it is specific to the Conversations, as soon as I uninstalled it, it stopped. Of course, Thunderbird's own thread view is not particularly sophisticated compared to the Conversations - so it could be that it is somehow a display issue, not indexing... So, perhaps embarrassing, I have received your answer in email, and I replied to it (copied it over here I am only adding this sentence). And then I have received an email from LinkedIn, which was added to our conversation. So, you seem to be right, it was Thunderbird's indexing...

In any case, I have uninstalled the Conversations only temporarily, I will put it back as soon as it is plausible that it stops hanging. In the meantime, happy to help to test - unfortunately, cannot help with the coding.

**Comment by scheinercc** [comment] 2020-08-08 05:52
@Standard8 I also see TB hanging more. In my case this is when navigating through a conversation a bit quicker.

TB 78.x.x
macOS 10.14.6

- Opening a conversation with several messages (6+, the more the better)
- Navigate from the 1st to the 2nd message, right after the 2nd loaded go to the 3rd and so on

Once I move to the next message and the view doesn't update anymore, I know hit the issue. CPU is on 100% and stays around there for 30-60 seconds for me.

If the issue doesn't appear with the last message, moving that tree back up can also lead to the result.

Not sure if it is related to the original post, but it might.

**Comment by Standard8** [comment] 2020-08-08 08:09
@scheinercc can you file a separate issue for that? That does indeed sound slightly different. Getting the output of the error console would be useful, as well as a [performance profile](https://github.com/thunderbird-conversations/thunderbird-conversations/wiki/Profiling-Conversation's-Performance)

**Comment by Standard8** [comment] 2020-08-08 09:05
On the performance front, I've found a [performance issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1658062) in how Thunderbird does its address book searches (which we use for displaying the correct contact names etc). That will help speed things up a little bit. Will hopefully be able to get that fix into one of the next couple of Thunderbird release builds.

I think there's still at least one other performance item related address book searches that's within Thunderbird, though fixing it is likely to be harder and probably won't make the 78 series.

However, I have some ideas on how to reduce the amount of queries that Conversations is doing - we're already fairly optimal but I think we could do more caching per session - so although the first time you select a thread might be a bit slower, it'd be faster the subsequent times.

There's potentially more, but from the profiles I've seen so far, the address book queries are the most expensive.

**Comment by scheinercc** [comment] 2020-08-09 12:26
> @scheinercc can you file a separate issue for that? That does indeed sound slightly different. Getting the output of the error console would be useful, as well as a [performance profile](https://github.com/thunderbird-conversations/thunderbird-conversations/wiki/Profiling-Conversation's-Performance)

Done  #1522

**Comment by Standard8** [comment] 2020-08-09 21:33
Just an update, in addition to the [address book performance issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1658062) I mentioned previously (within Thunderbird), I have found and filed patches for a [couple](https://bugzilla.mozilla.org/show_bug.cgi?id=1658116) [more](https://bugzilla.mozilla.org/show_bug.cgi?id=1658128) issues.

I'm not yet convinced that's all of the performance gain, we'll need to see what happens as they land (from what I can tell, they should make it into the next 78.x version).

As I said previously, I've also got ideas for how we can speed up other areas within Conversations, by caching the contacts, though that's proving difficult to work out all the edge cases that there are and how to handle them. Hopefully will have something soonish, but we'll have to see.

**Comment by rapostolo** [comment] 2020-08-12 07:55
I confirm the issue (MacOS)

**Comment by doits** [comment] 2020-08-12 10:52
Good news, thunderbird 80.0b3 fixes the problems for me! Looks like the performance issues found in thunderbird were the culprit.

Will those fixes be released in a 78.x release, too?

**Comment by Standard8** [comment] 2020-08-12 17:46
Yes, the fixes are going to be released in 78.2.0 as well, probably around the 25th Aug. Glad they are helping.

**Comment by Standard8** [comment] 2020-08-12 19:24
Actually, looks like they're going into a 78.1.2 which is likely to be released soon from the looks of it.

**Comment by Standard8** [comment] 2020-08-31 19:08
This does indeed seem much improved in the latest 78.2.0. I'm still hoping to get some more improvements into conversations itself, but for now we'll call this fixed.

**Closed by Standard8** 2020-08-31 19:08 UTC
Labels: bug, thunderbird issue

**Comment by klapanciusz** [comment] 2020-09-01 01:40
Thank you, I have just reinstalled Conversations and it works very well. Happy to have the missed add-on back - Thunderbird is only complete for me with Conversations. Thank you!

**Comment by ed244** [comment] 2020-11-23 08:53
I upgraded to Thunderbird 78.5.0 but still seeing the same issue: It's hanging again and again for several minutes .
I already started Thunderbird in save mode with add-ons disabled, but that did not help.
Then I tried to go back to version 68 which worked perfectly well before.
But now Thunderbird 68 complains about my profile, because its from a newer version.
How can I "migrate" my profile back to version 68 ?

**Comment by Standard8** [comment] 2020-11-23 08:57
@ed244 Please can you try and capture a performance profile in 78.5.0... without that, or at least some hint of what is happening, we're not going to be able to resolve this easily.

Details on how to capture a profile here: https://github.com/thunderbird-conversations/thunderbird-conversations/wiki/Profiling-Conversation's-Performance

Please file a new issue and state exactly what you're doing to trigger the hang, and link to the profile.

**Comment by ed244** [comment] 2020-11-24 07:24
yesterday I had performance recorder active for many hours but the problem did not show up.
But this morning it re-occured, but I was not able to start the performance recorder because thunderbird was not responding. I saw that it was consuming lot's of CPU for about 4-5 minutes until it was usable again.
I created a dump file via task manager if that is of any help.

**Comment by Standard8** [comment] 2020-11-24 08:05
It might be worth attempting to disable Conversations for a while and see if it reproduces.

Could it be on particularly large threads or something like that?

**Comment by ed244** [comment] 2020-11-24 08:32
Now I was able to reproduce the issue while performance recorder was active.
But i wonder if the data are correct, because performance recorder did not response either during that time
[Thunderbird_78.5_profile.json.zip](https://github.com/thunderbird-conversations/thunderbird-conversations/files/5588413/Thunderbird_78.5_profile.json.zip)

**Comment by ed244** [comment] 2020-11-24 08:46
Today it's horrible. I'm face the issue every 15 -20 mins or so.
I'm using Thunderbird 78.5 the same way as I was using version 68. Same mail accounts etc.
I have lots of mails in my inbox (~15000) but I'm not aware of  particularly large threads. What does "particularly large" mean?

**Comment by Standard8** [comment] 2020-11-24 09:57
Thank you for the profile - it did work. The hang stacks are basically entirely calendar code - my best guess is there's some recurring items in your calendar which are for some reason triggering this.

In any case it doesn't look like Conversations, so I've filed a bug on your behalf for the issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1679132

If you can add a little more information directly on that bug about your operating system and maybe what your calendars consist of, that might be useful for them to be able to figure out what's happening.

**Comment by ed244** [comment] 2020-11-24 14:04
one more question: I wonder where I can see (and change) my account setting for Calendar?
If I open account settings I can only see setting for e-mail (IMAP,SMTP)

**Comment by ed244** [comment] 2020-11-24 14:06
Found it under Calendar. Please ignore.

**Comment by Standard8** [comment] 2020-11-24 17:32
@ed244 Please see the comments on that bug. In particular, it looks like you have the `calendar.icaljs` preference set to true (See config editor in preferences) - that is experimental and not yet supported.

Please direct any more comments to that bug, as that's where we can get most help. We don't need to ping everyone here who are just interested in Conversations.

https://bugzilla.mozilla.org/show_bug.cgi?id=1679132
