### ISSUE TITLE
Conversation is not loaded due to "Message no longer exists"

### ISSUE THREAD

**Issue by cfenollosa** [thunderbird-conversations/thunderbird-conversations#1557] opened 2020-11-15 17:59 UTC
* **Thunderbird version:** 68.10.0
* **Thunderbird Conversation version:** 3.1.24
* **Operating System:** Ubuntu 20.04

**What did you do?** Click on a message in the message list

**What did you expect to happen?** Display the conversation on the message pane

**What actually happened?** The contents of the message pane do not change -- they still display the previous conversation 

The error console complains that:

```
Error: "Message no longer exists"
    toReactData chrome://conversations/content/modules/message.js:421
```

Note that this issue is similar to #1496 but instead of getting a blank window on the message pane, the contents of the message pane do not change.

This has nothing to do with attachments, as the bug happens for messages without attachments too.

Restarting thunderbird fixes it, until a few minutes later when the behavior is repeated.

I have not been able to trigger the bug on purpose. It seems to start happening after some point in time, then it triggers for about 50% of my conversations.

**Comment by Standard8** [comment] 2020-11-23 08:45
Do you detach/delete attachments or do other things that might modify a message after you've viewed it?

As mentioned in the other issue TB has a bug that means sometimes changes don't get handled properly and that breaks add-ons trying to look at the messages. Unfortunately I've not been able to track down the exact cause yet.

**Comment by cfenollosa** [comment] 2020-11-24 08:12
No, I've never used the detach/delete attachments feature.

As per "other things that might modify a message", what those might be? My workflow is very normal: receive emails, reply, forward, archive...

Maybe there is something about saving drafts? Compating folders? I'm not a Thunderbird expert so I can't tell, but if you give me some ideas I might try to trigger things and try to reproduce the bug

**Comment by Standard8** [comment] 2020-11-24 08:15
Drafts might do it, but I've not been able to reproduce anything around those so far.

Do you use any other add-ons?

**Comment by cfenollosa** [comment] 2020-11-24 16:01
This is my add-on list. Maybe we can find some suspects?

![image](https://user-images.githubusercontent.com/2249551/100118969-a8ec2900-2e76-11eb-8069-a67757a21312.png)

**Comment by Standard8** [comment] 2020-12-13 19:25
The only thing I can suggest here at the moment is to try updating to the latest Thunderbird and Conversations versions, and see if that helps.

I would suspect this could be something to do with particular messages, but it is hard to tell.

**Comment by Standard8** [comment] 2021-03-06 15:02
I'm closing this out, since we haven't had more reports of it, and we have no idea what caused it. Hopefully updating to the latest of both Thunderbird & Conversations has helped address this.

**Closed by Standard8** 2021-03-06 15:02 UTC
