### ISSUE TITLE
Thunderbird Conversations does not show content of messages in message pane any more

### ISSUE THREAD

**Issue by k11i** [thunderbird-conversations/thunderbird-conversations#1834] opened 2022-05-04 11:14 UTC
* **Thunderbird version:** 91.8.0
* **Thunderbird Conversation version:** 4.0.13
* **Operating System:** Debian Linux (stable)

**What did you do?**
Tried to display a message or message conversation

**What did you expect to happen?**
Message should be shown,

**What actually happened?**

Since today Messages are not shown in the message pane (well, the one on the right, where the content of the mails usually is show). I get the string "Loading ...." in the top bar of the pane (in the bar where the icons for delete conversation, archive conversation, show in tab and so on are).

If I deactivate Thunderbird Conversations, the message content is shown, but that is naturally not what I want. ;-)

This is the only message in my ErrorConsole after activating the extension and selecting two mails one after the other to show:

`13:08:42.872 gloda.collection: caught exception from listener in onItemsAdded: resource:///modules/gloda/Collection.jsm:588: RangeError: too many arguments provided for a function call Collection.jsm:603:13
    _onItemsAdded resource:///modules/gloda/Collection.jsm:603
    onItemsAdded resource:///modules/gloda/GlodaDatastore.jsm:154
    _onItemsAdded resource:///modules/gloda/Collection.jsm:601
    onItemsAdded resource:///modules/gloda/GlodaDatastore.jsm:154
    _onItemsAdded resource:///modules/gloda/Collection.jsm:601
    onItemsAdded resource:///modules/gloda/GlodaDatastore.jsm:154
    handleCompletion resource:///modules/gloda/GlodaDatastore.jsm:444
`

It took a while for this error message to appear. In the meantime, Thunderbird spiked up to 160% CPU and the error message appeared after CPU-Usage of Thunderbird went down again.

Edit: Downgrading to 4.0.12 and restarting Thunderbird helped (deactivating and reactivating the extension did not show messages).

**Comment by nean-0** [comment] 2022-05-04 20:56
Happens to me as well. When downgrading to the earlier version 4.0.12 it works fine.
MozillaThunderbird  91.8.0-150200.8.65.1 on opensuse 15,3

**Comment by GottHeit** [comment] 2022-05-05 06:32
Facing the same problem. Can see a continously growing spike in RAM Usage. Have to kill the process and to restart TB. 
If conversions Addon is deactivated everything works well. 
First thought was it may depend on the age or size and therby the sync-date of mails but cannot really reproduce as it happens for some newly written drafts too if changing to drafts folder to check the mail again or to apply some changes. 

Downgrading to 4.0.12 works for me aswell for the moment.

Thunderbird 91.9.0

**Comment by nean-0** [comment] 2022-05-05 11:34
Yes, should have mentioned that.  One of the cores of the CPU runs at 100% and RAM usage goes to fill up all available space and then continues to do the same with swap space.

**Comment by Standard8** [comment] 2022-05-05 20:10
4.0.14 is out now which will hopefully help. If it is still an issue please include exact details of what you are doing to trigger it, and include logs from the error console.

**Comment by Standard8** [comment] 2022-05-07 07:44
I've not heard of more issues so tentatively closing this as fixed.

**Closed by Standard8** 2022-05-07 07:44 UTC
