### ISSUE TITLE
Wrong "from" account chosen when replying to emails

### ISSUE THREAD

**Issue by x-ji** [thunderbird-conversations/thunderbird-conversations#1749] opened 2021-11-08 11:47 UTC
- Thunderbird: 91.3.0 (64-bit)
- OS: MacOS 12.0.1
- Extension: 4.0.5

This seems to be a similar issue to https://github.com/thunderbird-conversations/thunderbird-conversations/issues/1730

**What did you do?**
Click on the quick reply button or the reply icon (which opens a new window) from the conversation view of a message in the inbox of account A.

**What did you expect to happen?**
The "From" address is correctly chosen as account A, the account I received the email at.

**What actually happened?**
A different "From" address is chosen by default, that associated with account B.

However, if I right click on the message and choose "reply to all" or "reply to sender only" from the TB context menu, account A is chosen as the sender correctly.

This happens for all conversations in that inbox, no matter how old it is. All the conversations only have account A as the recipient and are never intended for account B.

The folder is just the normal inbox folder for account A, and I don't see it associated with account B in any way.

Interestingly, I have 3 further accounts in the same Thunderbird, but this issue doesn't happen for any of them, i.e. the correct sender is chosen if I click on the Reply button.

All accounts are from different email providers.

Let me know if you need more info @Standard8 

cc @klapanciusz as he seems to report that he is also still encountering this issue.

**Comment by klapanciusz** [comment] 2021-11-08 16:53
Thanks for including me x-ji. You are right, the same issue persists for me, although the situation somewhat improved with 4.0.4.

Still could not replicate the pattern, although I managed to eliminate some plausible causes and correlations. For instance, now I had a single email from one person, addressed only to my personal email address (gmail, but with my own domain), I was in the 'To:' field, nobody else in the email, and the email was new not a response to a previous conversation. When I have clicked inside the quick reply or hit the reply button, it brought up my work email in the From:' field.

Nice catch that this does not happen with right-click!

**Comment by Standard8** [comment] 2021-11-12 09:52
Please can you try out this version of the add-on. It is the same as the currently released version, but with the addition of some logging and one minor change to the algorithm (though I don't think that'll fix this).

https://www.thebanners.uk/conversations-reply-logging.xpi

To test it:

* You'll need to right-click that link above and "Save Link As..."
* Go to Tools -> Add-ons in Thunderbird, and select Extensions if it isn't already.
* Near the top-right, there's a cog symbol, click that and select "Install Add-on from File". Select the file, and allow it to install.
* Once installed, restart Thunderbird.
* Open the Error Console via Tools -> Developer Tools -> Error Console or pressing ctrl/cmd-shift-J
* Select a message that is problematic
  * Look at the error console at this stage, there should be some messages about "id1 <email>" - these are the identity id to email mappings that Thunderbird is telling Conversations about.
* Select the reply button or quick reply
  * Look at the error console again. There will be information about which id is being selected and why.

This is where you'll then need to share the logs / explain what's happening. 

I don't need to have the email addresses themselves - though if it looks obvious that emails aren't being matched when they should be, we might have to dig into why that is.

That version of the add-on should also automatically update to the next version when it gets release so in theory you don't need to reinstall the current version.

**Comment by klapanciusz** [comment] 2021-11-12 13:28
Mark, it seems that we are onto something with this - will continue 
testing later, only had a short time now, but here is what I have found:

 1. First, I had to find an email with which it gives the wrong "from" -
    it took a while, but finally it did. It was an email sent to my work
    address. On selecting the message id1 was right (my work email), id2
    was my personal email, and id3 was the third account I have, from
    which I have never sent an email to this person and I have not sent
    an email from this account for at least 2 years (so not since I have
    the latest Thunderbird install).
 2. When clicked quick reply or the reply button, it was sending from my
    personal email.
 3. Restarted Thunderbird, went back to the same message, and this time
    it was sending from the right address... So the error is not
    consistent, something is probably rebuilt on restart.

There is a lot of red stuff in my error console, but I don't understand 
most of it. Will do some more testing later and send you the log. I will 
also try it on both my laptop and my desktop at work.

Thank you very much.

Viktor

**Comment by Standard8** [comment] 2021-11-12 13:47
You can probably get away with turning off "Errors" in the console - there's a toggle button at the top.

Additionally, if you go back into Add-ons, next to Conversation's there should be a spanner symbol - click that, then scroll down and tick the box next to debugging. After that restart Thunderbird.

Based on what you've said, I'm particularly interested if maybe that's a recent message you've got and Thunderbird hasn't indexed it yet. The extra logging will output things like "Streaming the message because Gloda has not indexed it, this will be slower". If that's the case, this is a different code path and could be a good clue.

Now I've written that, I've just remembered - try also testing emails in your deleted or junk folders. They aren't indexed by default so it may be easier to reproduce consistently.

**Comment by klapanciusz** [comment] 2021-11-12 22:30
Thank you Mark. I did that - although it is worrying that there are so 
many errors happening 😁

So, the curious thing is that all afternoon at work on my desktop the 
error did not occur (previously it was happening the same way as on my 
laptop, and the setup is more or less identical). As I got home, it got 
a few right, then I selected an email received last night (technically 
today, but for my purpose yesterday, so it must have been indexed). 
After just clicking on the email, the, the console did not display any IDs.

Here is what I have copied from the console (I assume that only the last 
two lines are relevant):

**********************************************

Start unmangle links display.js:50:9

[l10nregistry] Attempting to synchronously load file 
resource:///chrome/en-US/locale/en-US/calendar/toolkit/intl/languageNames.ftl 
while it's being loaded asynchronously. L10nRegistry.jsm:597:19
[l10nregistry] Attempting to synchronously load file 
resource:///chrome/en-US/locale/en-US/calendar/toolkit/intl/regionNames.ftl 
while it's being loaded asynchronously. L10nRegistry.jsm:597:19
2021-11-12T22:13:39.383Z [info] WindowId=174 "setCurrentLang en-GB" 
ad.js:106:13
2021-11-12T22:13:39.389Z [info] WindowId=174 "Changing label to: 
Remembered en-GB" ad.js:106:13
Found contact with identity ***@***.*** id1 902.bundle.js:5253:17
Final identity id1 902.bundle.js:5274:13

**********************************************

So, as far as I can tell, according to the console, the identification 
was correct, as I have received the email to my work account and wanted 
to reply from that - however, as I have clicked into the quick reply 
field, it was attempting to answer from my personal account, which at 
that time did not appear in the console at all. Turned the errors back 
on, and it had an error message before and after saying "Not a valid 
compose window".

Now I have turned on the debugging in the Conversation, and will restart 
my laptop and be back with further comments.

**Comment by klapanciusz** [comment] 2021-11-12 22:48
So, having turned on the debugging for the Conversations and restarting 
Thunderbird, I have clicked on the same message as before, and this time 
the quick reply was to go, correctly from my work account - however, 
this is what the console displayed:

************************************************

Found contact with identity ***@***.*** id2 902.bundle.js:5253:17
Final identity id2 902.bundle.js:5274:13

************************************************

It seems to me that my work email should have been id1, as that was in 
the 'to' field of the email to which I was replying...

I do not have many items in my deleted folder, as I use the setup in 
Thunderbird to empty my deleted folder on every exit - I tried with a 
freshly deleted email, but it was fine. Similar with junk - it is empty...

Just occurred to me if it was possible that the reason is a clash with 
the Compact Header add-on; it was useful when there was no Conversation 
- will remove it and test again.

**Comment by klapanciusz** [comment] 2021-11-12 23:00
Okay, here is my last attempt for the day. This time personal email 
folder, here is hte console content:

******************************************

Conversations.msgWindowApi: Intercepted message load, 1 message(s) 
selected msgWindowApi.js:705:13

Conversations.msgWindowApi: New conversation: 11 Old conversation: 10 
msgWindowApi.js:674:13
Conversations.Conversation: Outputting
Array [ "GF 
***@***.***", 
"GM 
***@***.***"]
conversation.js:512:9
Filtering out duplicates:
Array [ 
***@***.***", 
***@***.***"]
902.bundle.js:701:17
Load took (ms): 86 902.bundle.js:1529:21
Marking selected message as read stub.bundle.js:1586:23
Found contact with identity ***@***.*** id2 902.bundle.js:5253:17
Final identity id2 902.bundle.js:5274:13

******************************************

So, my personal email, which was in the 'to' field, got identified as 
id2, however, the response was to go from my work email. Overall, it 
seems to me that the identified id1-2-3 is not getting into the 'from' 
field...

Thank you Mark, I hope that this helps.

**Comment by Standard8** [comment] 2021-11-12 23:18
@klapanciusz so just to check... the above tests were all done with quick reply?

Are you able to replicate the same issue with Conversation's reply button that opens up the compose window? Opening the compose window is a completely different code path, so I'm hoping that isn't wrong as well.

I have spotted one simplification that I could do in the code, though if that is causing it, it probably means Thunderbird's account/identity system is broken somehow. I'll try and fix that and add a bit more debug over the weekend.

**Comment by klapanciusz** [comment] 2021-11-12 23:30
Yes Mark. I have used the quick reply, but also tested with the reply 
button in Conversations. For the same message the outcome is the same, 
until I restart Thunderbird - for now I cannot tell if the problem is 
ever repeated after restart, but I have seen several instances when it 
did not repeat. However, if I right-click the message and choose reply 
from the context menu or if I use the Thunderbird toolbar button, the 
'from' is correct. Can the problem be somehow in how Thunderbird hands 
over something to Conversation? Sorry, if I do not make much sense, only 
as the two Thunderbird ways are working, the two Conversations are not 
although they are two distinct codes sounds to me as if it is somewhere 
in how they interface with each other...

Thank you!

**Comment by Standard8** [comment] 2021-11-14 11:31
I've just done a few updates and added some more logging, the new version is here: https://www.thebanners.uk/conversations-reply-logging-2.xpi

I don't think this will fix anything for you, as it primarily adjusts how the identities are handled if the email doesn't have an addressed email that matches one of your ids.

However it should at least add some more logging.

For Thunderbird vs Conversations - Conversations is completely in charge of quick reply and the identity passed to the compose window of Thunderbird. Thunderbird's handling the context menu completely itself.

So, if it is saying in the logs that it is picking the right identity, then it should be displaying that in quick reply. If it isn't then somehow Thunderbird would have to be returning different emails for the same identity, which doesn't quite seem possible.

For the compose window Conversations passes it the id. I'm starting to wonder if #1725 has more of an effect than just getting the field wrong. I could be wrong there though.

In any case, procedure for this version should be roughly the same. Though, can you:

* After installing & restarting Thunderbird. Select any message and copy and paste the account/id map from the console? It logs in two sections the id map with numbers for the emails, and the separate list of numbers with emails. I don't need the separate list, though it might be useful to know which ids you identify as "work" and "personal".
* The above lists will be displayed every time you restart Thunderbird and select a new email. It might be useful just to try it a few times and make sure they're consistent. They should be, but just in case.
* Please also try and reproduce the quick reply output and copy the messages from the console.
* Maybe also copy & paste some of these errors/warnings that you're seeing. If they're mentioning calendars, probably not worth it. I'm starting to wonder if they are relevant here.

**Comment by klapanciusz** [comment] 2021-11-14 15:29
Thanks Mark - yeah, definitely more logging 😁 Could barely find the 
beginning, I even deleted all stuff from the error console once to be 
able to follow. Yesterday, I have re-enabled the error messages, as the 
same thought occurred to me as well, so I am now posting the log with 
those in.

When I intentionally want to reproduce the error then it does not always 
work, of course. I am wandering if it is happening only with people with 
whom I had earlier conversations from multiple email accounts - for now 
it is possible. With you, for instance, I only used my personal email, 
and it never went wrong.

So, here is the newest error case - it is part of a long conversation 
that had errors previously, will try to find 'cleaner' examples later. 
Here is the log:

*******************************************

Marking selected message as read stub.bundle.js:1586:23
NS_ERROR_NOT_AVAILABLE: ActivityManager.jsm:129
Error: Not a valid compose window undefined
Found contact with identity ***@***.*** id1 902.bundle.js:5253:17
Final identity id1 902.bundle.js:5276:13
window created background.js:11:13
2021-11-14T15:12:19.757Z [debug] WindowId=308 "ad: init" ad.js:106:13
2021-11-14T15:12:19.757Z [debug] WindowId=308 "dispatching event " 
ad.js:106:13
2021-11-14T15:12:19.757Z [debug] WindowId=308 
"{\"type\":\"plugins-initialized\"}" ad.js:106:13
window.controllers/Controllers is deprecated. Do not use it for UA 
detection. blank <about:blank?>
2021-11-14T15:12:20.044Z [debug] WindowId=308 "Setting key: 
migrations_applied" ad.js:106:13
2021-11-14T15:12:20.044Z [debug] WindowId=308 
["201101010000","201102130000","201106032254","201210192306","201211112134","202003161545","202003231651","202106051955","202106271139"] 
ad.js:106:13
2021-11-14T15:12:20.054Z [info] WindowId=308 "before initialize data" 
ad.js:106:13
2021-11-14T15:12:20.055Z [debug] WindowId=308 "events registered" 
ad.js:106:13
2021-11-14T15:12:20.056Z [debug] WindowId=308 "increasing stats.usages" 
ad.js:106:13
2021-11-14T15:12:20.056Z [debug] WindowId=308 "dispatching event " 
ad.js:106:13
2021-11-14T15:12:20.057Z [debug] WindowId=308 "{\"type\":\"load\"}" 
ad.js:106:13
Security Error: Content at 
moz-nullprincipal:{5d0a2a73-ab20-4eb7-a326-f0794fe10145} may not load or 
link to 
***@***.***:993/fetch%3EUID%3E/INBOX%3E391491?header=quotebody&part=1.2&filename=image001.png. 

Security Error: Content at 
moz-nullprincipal:{5d0a2a73-ab20-4eb7-a326-f0794fe10145} may not load or 
link to 
***@***.***:993/fetch%3EUID%3E/INBOX%3E391491?header=quotebody&part=1.3&filename=image002.png. 

Start unmangle links display.js:50:9
Rewrote 
https://eur02.safelinks.protection.outlook.com/?url=https%3A…2FSuCgQtm6gXHR3fX5Z%2B%2FeH%2FIO0agYjIupRZ7aOE%3D&reserved=0 
<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdoi.org%2F10.1111%2Fcaim.12471&data=04%7C01%7Cviktor.dorfler%40strath.ac.uk%7C286dbf6fb098434ac33d08d9a6ffec76%7C631e0763153347eba5cd0457bee5944e%7C0%7C0%7C637724440416038164%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=cR%2FZ%2FSuCgQtm6gXHR3fX5Z%2B%2FeH%2FIO0agYjIupRZ7aOE%3D&reserved=0> 
to https://doi.org/10.1111/caim.12471 
<https://doi.org/10.1111/caim.12471> display.js:31:15
Rewrote 
https://eur02.safelinks.protection.outlook.com/?url=https%3A…wcXCUZ%2Bmh7nLc%2FMN5XE95f3JP4sr%2BvIq6m9SsXb8%3D&reserved=0 
<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2F2021.aom.org%2Fmeetings%2Fvirtual%2FhmuBmLuyLgWink8uH&data=04%7C01%7Cviktor.dorfler%40strath.ac.uk%7C286dbf6fb098434ac33d08d9a6ffec76%7C631e0763153347eba5cd0457bee5944e%7C0%7C0%7C637724440416038164%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=%2BXgwcXCUZ%2Bmh7nLc%2FMN5XE95f3JP4sr%2BvIq6m9SsXb8%3D&reserved=0> 
to https://2021.aom.org/meetings/virtual/hmuBmLuyLgWink8uH 
<https://2021.aom.org/meetings/virtual/hmuBmLuyLgWink8uH> display.js:31:15
Rewrote 
https://eur02.safelinks.protection.outlook.com/?url=http%3A%…ta=7wCBGs0CLySGJZlPfAD4OHwyMRt7qpKXKnccVW07dAE%3D&reserved=0 
<https://eur02.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.businesslaw.curtin.edu.au%2F&data=04%7C01%7Cviktor.dorfler%40strath.ac.uk%7C286dbf6fb098434ac33d08d9a6ffec76%7C631e0763153347eba5cd0457bee5944e%7C0%7C0%7C637724440416048125%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=7wCBGs0CLySGJZlPfAD4OHwyMRt7qpKXKnccVW07dAE%3D&reserved=0> 
to http://www.businesslaw.curtin.edu.au/ 
<http://www.businesslaw.curtin.edu.au/> display.js:31:15
Rewrote 
https://eur02.safelinks.protection.outlook.com/?url=https%3A…=7%2BcuugN3ZSyw8hAoCGr6Qozp2k5hQ6nDhNlneVaC5zA%3D&reserved=0 
<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuk.sagepub.com%2Fen-gb%2Feur%2Fmaking-strategy%2Fbook234090%23ackermann&data=04%7C01%7Cviktor.dorfler%40strath.ac.uk%7C286dbf6fb098434ac33d08d9a6ffec76%7C631e0763153347eba5cd0457bee5944e%7C0%7C0%7C637724440416048125%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=7%2BcuugN3ZSyw8hAoCGr6Qozp2k5hQ6nDhNlneVaC5zA%3D&reserved=0> 
to https://uk.sagepub.com/en-gb/eur/making-strategy/book234090#ackermann 
<https://uk.sagepub.com/en-gb/eur/making-strategy/book234090#ackermann> 
display.js:31:15
Rewrote 
https://eur02.safelinks.protection.outlook.com/?url=http%3A%…2BW8%2FJXIsczvsr1zPs2vZWTyyU5daNxlmDE3EHe4XhhM%3D&reserved=0 
<https://eur02.safelinks.protection.outlook.com/?url=http%3A%2F%2Feu.wiley.com%2FWileyCDA%2FWileyTitle%2FproductCd-1118605926.html&data=04%7C01%7Cviktor.dorfler%40strath.ac.uk%7C286dbf6fb098434ac33d08d9a6ffec76%7C631e0763153347eba5cd0457bee5944e%7C0%7C0%7C637724440416058081%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=%2BW8%2FJXIsczvsr1zPs2vZWTyyU5daNxlmDE3EHe4XhhM%3D&reserved=0> 
to http://eu.wiley.com/WileyCDA/WileyTitle/productCd-1118605926.html 
<http://eu.wiley.com/WileyCDA/WileyTitle/productCd-1118605926.html> 
display.js:31:15
Security Error: Content at 
moz-nullprincipal:{5d0a2a73-ab20-4eb7-a326-f0794fe10145} may not load or 
link to 
***@***.***@outlook.office365.com:993/fetch%3EUID%3E/INBOX%3E391491?header=quotebody&part=1.2&filename=image001.png. 

Security Error: Content at 
moz-nullprincipal:{5d0a2a73-ab20-4eb7-a326-f0794fe10145} may not load or 
link to 
***@***.***@outlook.office365.com:993/fetch%3EUID%3E/INBOX%3E391491?header=quotebody&part=1.3&filename=image002.png. 

2021-11-14T15:12:21.097Z [info] WindowId=308 "trying to get by 
heuristics" ad.js:106:13
2021-11-14T15:12:21.099Z [info] WindowId=308 "Changing label to: No 
language saved for these recipients" ad.js:106:13
2021-11-14T15:12:21.281Z [info] WindowId=308 "trying to get by 
heuristics" ad.js:106:13
2021-11-14T15:12:47.361Z [info] WindowId=308 "trying to get by heuristics"

*******************************************

So, it correctly identified my ***@***.*** as id1, but then it went on 
to reply from my personal email... It also seems to me that it does not 
actually do a complete id mapping, stops as soon as one id is found.

Hopefully can get the next one with a new email example.

Thanks Mark!

Viktor

**Comment by klapanciusz** [comment] 2021-11-14 15:41
Okay, here is a clean example - it is a person from whom I have never 
received an email before, as far as I can tell. I have used the reply 
button within Conversation, but tested, it is the same with the quick reply:

*****************************************************

Error: Not a valid compose window undefined

Found contact with identity ***@***.*** id1 902.bundle.js:5253:17
Final identity id1 902.bundle.js:5276:13
window created background.js:11:13
2021-11-14T15:32:01.429Z [debug] WindowId=470 "ad: init" ad.js:106:13
2021-11-14T15:32:01.430Z [debug] WindowId=470 "dispatching event " 
ad.js:106:13
2021-11-14T15:32:01.430Z [debug] WindowId=470 
"{\"type\":\"plugins-initialized\"}" ad.js:106:13
window.controllers/Controllers is deprecated. Do not use it for UA 
detection. blank <about:blank?>
2021-11-14T15:32:01.806Z [debug] WindowId=470 "Setting key: 
migrations_applied" ad.js:106:13
2021-11-14T15:32:01.807Z [debug] WindowId=470 
["201101010000","201102130000","201106032254","201210192306","201211112134","202003161545","202003231651","202106051955","202106271139"] 
ad.js:106:13
2021-11-14T15:32:01.817Z [info] WindowId=470 "before initialize data" 
ad.js:106:13
2021-11-14T15:32:01.818Z [debug] WindowId=470 "events registered" 
ad.js:106:13
2021-11-14T15:32:01.818Z [debug] WindowId=470 "increasing stats.usages" 
ad.js:106:13
2021-11-14T15:32:01.819Z [debug] WindowId=470 "dispatching event " 
ad.js:106:13
2021-11-14T15:32:01.820Z [debug] WindowId=470 "{\"type\":\"load\"}" 
ad.js:106:13
Start unmangle links display.js:50:9
2021-11-14T15:32:02.855Z [info] WindowId=470 "trying to get by 
heuristics" ad.js:106:13
2021-11-14T15:32:02.856Z [info] WindowId=470 "setCurrentLang en-GB" 
ad.js:106:13
2021-11-14T15:32:02.859Z [info] WindowId=470 "Changing label to: Guessed 
en-GB" ad.js:106:13
2021-11-14T15:32:02.909Z [info] WindowId=470 "trying to get by 
heuristics" ad.js:106:13

*****************************************************

Despite this, the reply was leaving from my personal email.

Does this help? I am sorry if I am doing something incorrectly, I am not 
sure I understood all the instructions 😁 It could have something in 
common with #1725 
<https://github.com/thunderbird-conversations/thunderbird-conversations/issues/1725>, 
as that also only happens when the Conversation reply button is used, 
not if reply is from the context menu (which I did not notice until now, 
as I never use the context menu reply...)

Thanks!

**Comment by Standard8** [comment] 2021-11-14 17:50
Unfortunately that doesn't really help at the moment. Can you try these two items please?

> * After installing & restarting Thunderbird. Select any message and copy and paste the account/id map from the console? It logs in two sections the id map with numbers for the emails, and the separate list of numbers with emails. I don't need the separate list, though it might be useful to know which ids you identify as "work" and "personal".
> 
> * The above lists will be displayed every time you restart Thunderbird and select a new email. It might be useful just to try it a few times and make sure they're consistent. They should be, but just in case.

**Comment by klapanciusz** [comment] 2021-11-14 20:57
Sorry - is this what you've meant?

*************************************************

account3 id1 account3 1 background.bundle.js:1269:17

account4 id2 account4 2 background.bundle.js:1269:17
account5 id3 account5 3 background.bundle.js:1269:17
id1 1 background.bundle.js:1281:17
id2 2 background.bundle.js:1281:17
id3 3 background.bundle.js:1281:17
Emails to numbers: background.bundle.js:1285:13
1 ***@***.*** background.bundle.js:1288:15
2 ***@***.*** background.bundle.js:1288:15
3 ***@***.***

*************************************************

If the order in 'account settings' is anything to go by, the order there 
is the same as the last three lines of this log.

Will now do the repetitions and check consistency.

**Comment by klapanciusz** [comment] 2021-11-14 21:03
Repeated it 3 times, it is all the same - will check from time to time 
over the next few days, but I would be surprised if it was different.

**Comment by Standard8** [comment] 2021-11-14 22:27
Ok, well at least that is consistent.

I've got one more version now: https://www.thebanners.uk/conversations-reply-logging-3.xpi

This adds logging between the time where it decides what to use for quick reply, and where it actually displays it. In theory they shouldn't be different, but that's not what you're seeing, so lets verify that. Unfortunately I can't do this for compose.

When you click quick reply you should now see output such as:

```
No identity found so far, using account account7
Found identity id5
Final identity id5
quick reply using identity id id5
quick reply email mark@****
quick reply final using id5
initCompose using identityId id5
compose final from identity mark@**** id5
```

Hopefully everything there is consistent, but given your experience so far, I'm kinda hoping it isn't (otherwise I start running out of ideas).

**Comment by klapanciusz** [comment] 2021-11-15 21:35
Mark, as I was working today on both my Uni desktop and my laptop, and 
you have asked me to send the initial id mapping, I have realised that I 
have the same accounts on the two computers but in different order - 
could this in some weird way cause the problem? On my laptop, it is 
private, work, other, and on my desktop it is work, private, other.

Will now do some testing with the new version.

**Comment by klapanciusz** [comment] 2021-11-15 21:50
Here is what I have got with a mistaken reply:

*******************************************

Found contact with identity ***@***.*** id2 902.bundle.js:5253:17

Final identity id2 902.bundle.js:5276:13
quick reply using identity id id2 902.bundle.js:5601:15
quick reply email ***@***.*** 902.bundle.js:5603:15
quick reply final using id2 902.bundle.js:5668:15
initCompose using identityId id2 902.bundle.js:5456:15
compose final from identity ***@***.*** id2 902.bundle.js:5467:15

*******************************************

So, it seems to me that we do have a catch. It correctly identified my 
personal email, but then initiated the reply from my work email. There 
is a possible explanation of how the id-s are stored. When it originally 
mapped my emails (see below), id1 was personal, id2 was work. Now it 
identified, for whatever reason, my personal email (correctly) but 
associated it with id2 (which was previously my work id), and when it 
used id2 for response, it used the content which was in it - perhaps 
which was in it previously... In any case, here is the original mapping:

****************************************

account3 id1 account3 1 background.bundle.js:1269:17

account4 id2 account4 2 background.bundle.js:1269:17
account5 id3 account5 3 background.bundle.js:1269:17
id1 1 background.bundle.js:1281:17
id2 2 background.bundle.js:1281:17
id3 3 background.bundle.js:1281:17
Emails to numbers: background.bundle.js:1285:13
1 ***@***.*** background.bundle.js:1288:15
2 ***@***.*** background.bundle.js:1288:15
3 ***@***.*** background.bundle.js:1288:15

****************************************

Are we now onto something? 😁

**Comment by Standard8** [comment] 2021-11-15 21:59
So in your example:

```
Found contact with identity ***@***.*** id2 902.bundle.js:5253:17

Final identity id2 902.bundle.js:5276:13
quick reply using identity id id2 902.bundle.js:5601:15
quick reply email ***@***.*** 902.bundle.js:5603:15
quick reply final using id2 902.bundle.js:5668:15
initCompose using identityId id2 902.bundle.js:5456:15
compose final from identity ***@***.*** id2 902.bundle.js:5467:15
```

Were the contact emails the same all the way through, or was the first one different to the second two?

**Comment by klapanciusz** [comment] 2021-11-15 22:20
The first one was different (that was the correct one). I have changed 
the emails in the example, so initially it identified my personal email 
***@***.***) and the other two were my work email ***@***.***)

**Comment by Standard8** [comment] 2021-11-15 22:22
Oh! So all I see for your emails are the same thing `***@***.***`. I guess github is replacing them for privacy. Maybe you could use just `workemail` and `personalemail`?

**Comment by Standard8** [comment] 2021-11-15 22:22
(i.e. don't use the @ symbol).

**Comment by klapanciusz** [comment] 2021-11-15 22:33
Sorry - I had no idea, I was replying from Thunderbird. Here it is:

Initial id mapping:

*************************************

account3 id1 account3 1 background.bundle.js:1269:17

account4 id2 account4 2 background.bundle.js:1269:17
account5 id3 account5 3 background.bundle.js:1269:17
id1 1 background.bundle.js:1281:17
id2 2 background.bundle.js:1281:17
id3 3 background.bundle.js:1281:17
Emails to numbers: background.bundle.js:1285:13
1 personalemail background.bundle.js:1288:15
2 workemail background.bundle.js:1288:15
3 otheremail background.bundle.js:1288:15

*************************************

When replying with quick reply:

***************************************

ound contact with identity personalemail id2 902.bundle.js:5253:17

Final identity id2 902.bundle.js:5276:13
quick reply using identity id id2 902.bundle.js:5601:15
quick reply email workemail 902.bundle.js:5603:15
quick reply final using id2 902.bundle.js:5668:15
initCompose using identityId id2 902.bundle.js:5456:15
compose final from identity workemail id2 902.bundle.js:5467:15

***************************************

So, it seems to me that the initial mapping put personalemail in id1, 
workemail in id2, otheremail in id3, and then when using quick reply, 
personalemail was correctly identified, but associated with id2 (the 
workemail was there from the initial mapping), and then the answer went 
from my workemail...

**Comment by Standard8** [comment] 2021-11-16 08:16
Thank you for that, I think I have found the issue.

Do you have a contact in your address book which has both your personal email and your work email in it? If so, try temporarily removing one of those email addresses from the contact, and I think the issue will go away (in theory you shouldn't have to restart, but you might need to).

The problem is that in the background, we are caching the addresses used to speed up accessing the details. Unfortunately when we get the contacts from the address book, we're associating the identity to every email address returned for that contact. The first time it runs for an email we haven't cached yet, we get away with it, but when it pulls the second time, it hits the cache and it can get the wrong identity.

I can reproduce that locally, so as long as you can fix it if you remove one of the email addresses from the contact in the address book, then we should have the specific issue.

This will probably take me a few days to fix as I need to add some more tests for this and carefully change the code, but at least we have the specific issue now and it isn't in Thunderbird itself (which would take longer to fix).

**Comment by klapanciusz** [comment] 2021-11-16 15:33
Thanks Mark, it looks like that was it. I have removed my personalemail 
from my own contact, and now it is working. Will keep monitoring, but 
with a few dozen attempts with contact that I had most problems before 
it worked correctly every time now.

Thank you!

Best,

Viktor

**Comment by x-ji** [comment] 2021-11-16 19:55
I didn't get time in the past few days to try out the plugin but I've been following along. This seems to have worked in my case as well. Thanks a lot Mark and Viktor!

**Closed** 2021-11-18 22:38 UTC

**Comment by Standard8** [comment] 2021-11-27 09:39
Just to note 4.0.7 is out now which fixes this.
