### ISSUE TITLE
Saving attachment doesn't work if a file of the same name already exists.

### ISSUE THREAD

**Issue by rrossmair** [thunderbird-conversations/thunderbird-conversations#1813] opened 2022-03-25 02:00 UTC
* **Thunderbird version:**91.5.0 (64bit)
* **Thunderbird Conversation version:**4.0.12
* **Operating System:**Ubuntu 20.04.1

**What did you do?**Tried to save an attachment to a file. A file of the same name already existed in this directory.

**What did you expect to happen?**A Dialog to open asking whether to overwrite the existing file. In other words, behave like Thunderbird does without this addon.

**What actually happened?**Acted like the file was saved, but didn't actually save it. The older version was not replaced.

**Comment by Standard8** [comment] 2022-05-07 07:57
Exactly which options did you use when saving the attachment with this add-on and without?

I'm asking because as far as I know Conversations is using the exact same functions in code as Thunderbird uses, and on Mac the save dialog is prompting me if it already exists.

**Comment by Standard8** [comment] 2022-05-28 09:09
I'm closing this out as I can't reproduce and as far as I know, Conversations is using the same function routes as Thunderbird does. If more information is forthcoming, we might be able to take a look.

**Closed by Standard8** 2022-05-28 09:09 UTC
