### ISSUE TITLE
Show Reply instead of Reply All

### ISSUE THREAD

**Issue by TsinJu** [thunderbird-conversations/thunderbird-conversations#2082] opened 2024-02-23 11:41 UTC
* **Thunderbird version: 115.8.0 (64-Bit)
* **Thunderbird Conversation version: 4.1.6
* **Operating System: WIN 11

**What did you do? Where Time, Info and Dots Menu is it shows "Reply all" instead of reply (only)

**What did you expect to happen? Show Reply instead of Reply All

**Comment by Standard8** [comment] 2024-02-24 12:30
Conversations uses the same algorithm as Thunderbird to work out what to display for the primary reply button. This is generally focussed to displaying the most appropriate item for the email received.

I certainly wouldn't want to change the default here, or change how it is currently set up. Maybe if we had toolbar customisation (#278) we could have an option for a reply-only button. So I'll close this as a duplicate of that one.

**Closed by Standard8** 2024-02-24 12:30 UTC
