### ISSUE TITLE
Attachments not shown in encrypted/signed messages

### ISSUE THREAD

**Issue by Buratinator** [thunderbird-conversations/thunderbird-conversations#1619] opened 2021-03-23 15:56 UTC
* **Thunderbird version:** 78.8.1 (32-bit)
* **Thunderbird Conversation version:** 3.2.16
* **Operating System:** Windows 10 x64

**What did you do?** 
Received an encrypted email with an attachment. 

**What did you expect to happen?**
Was expecting to see the attachment as for unencrypted emails.

**What actually happened?**
The message is decrypted and shown in Conversations as expected, but the attachment is not shown. The paperclip in the attachment column is visible and in the classical view the attachment is displayed as expected.

The same happens with sent signed messages - the attachment can only be seen in the classical UI.

**Comment by Standard8** [comment] 2021-04-05 12:08
@Buratinator if you go into the add-on preferences (dig around in the add-on manager, there should be a preferences button in the three-dot menu next to Conversations), and enable `I love attachments`, does that fix it for you?

**Comment by Buratinator** [comment] 2021-04-05 12:11
That's been enabled for a long time and makes no difference for me, unfortunately.

**Comment by diekinderweltit** [comment] 2021-08-24 11:29
Close Thunderbird, delete the file `global-messages-db.sqlite` in your [Profile folder](http://kb.mozillazine.org/Profile_folder_-_Thunderbird), and restart Thunderbird.

[Link](https://github.com/thunderbird-conversations/thunderbird-conversations/wiki/FAQ/_compare/8a9f24c%5E...8a9f24c)

**Comment by Buratinator** [comment] 2021-08-24 11:38
Seems to have done the trick. I hope this is a permanent solution and won't come back when new messages arrive.

**Comment by Buratinator** [comment] 2021-08-25 10:19
The issue is back today, so I guess deleting `global-messages-db.sqlite` is not a permanent fix

**Comment by MartinX3** [comment] 2021-10-19 13:11
It doesn't help me.
Instead I only get a white area instead of the email content with an attachement.
And thunderbird is very slow each time I click on this email.

It's encrypted and the attachment is 8.3mb large.

**Comment by davidkopp** [comment] 2021-12-19 18:17
I have the same problem. Because of this issue I don't see any attachments of incoming mails. The whole communication between Thunderbird and my email provider (mailbox.org) is encrypted with PGP.
Because this issue is not tolerable for me I had to disable the add-on. I hope this issue will be fixed soon.

Thunderbird: 91.4.0 (64-bit)
Conversations Add-on: 4.0.8

**Comment by stratosjl** [comment] 2022-03-09 20:37
I have the same problem

**Comment by Standard8** [comment] 2022-03-10 07:52
Closing as this seems to be a duplicate of #1524.

**Closed by Standard8** 2022-03-10 07:52 UTC
Labels: investigate
