### ISSUE TITLE
Add support for Dark Reader

### ISSUE THREAD

**Issue by binarynoise** [thunderbird-conversations/thunderbird-conversations#1598] opened 2021-02-06 12:24 UTC
* **Thunderbird version:** 78.7.1 (32-Bit)
* **Thunderbird Conversation version:** 3.2.11
* **Operating System:** Windows 10 Pro 64bit 20H2

**What did you do?**
I installed the Dark Reader Add-On.

**What did you expect to happen?**
I expected Dark Reader to change the colors.

**What actually happened?**
When the Conversations Add-On is enabled, Dark Reader doesn't know what to do. Everything stays white.
If I disable Conversations, Dark Reader works as expected.

I am reporting here because I think it is an incompatibility issue that is rather resolved by this plugin. If you want I can also open the issue there too.

**Comment by Standard8** [comment] 2021-03-06 13:57
Hi, I'm not currently sure how dark reader is working, so it depends exactly on what it is doing as to what is causing the issue.

At the moment our dark mode support is really bad, so I'm inclined not to look into this straight away and fix it once we're able to complete that project: https://github.com/thunderbird-conversations/thunderbird-conversations/projects/5

**Comment by binarynoise** [comment] 2021-03-06 14:05
If we had proper dark mode/theme support, we wouldn't need Dark Reader support anyway. 
Anything I could do to help you?

**Comment by Standard8** [comment] 2021-03-06 14:07
Although Thunderbird has some dark mode support, I suspect that dark reader does things a little bit better. Though I could be wrong.

There's help wanted on the issues I filed, so feel free to take a look at those.

**Comment by rnc** [comment] 2021-03-06 14:11
While its not _quite_ a dark theme I am using https://github.com/conema/monterail-dark (which works fine with Conversations) and does give a reasonable compromise between dark theme and readability in my opinion :-)

**Comment by Gusted** [comment] 2021-03-06 21:46
> Hi, I'm not currently sure how dark reader is working, so it depends exactly on what it is doing as to what is causing the issue.

Just chipping in.
After some debugging, it seems like our content_scripts never get injected. As it seems like being denied due to Thunderbird-conversations `hijacking` the content pane on some URL which seems to be the problem. I'm thereby unsure how Thunderbird-conversations works exactly in this matter.

Regards,
Gusted

**Comment by Standard8** [comment] 2021-03-06 21:58
> After some debugging, it seems like our content_scripts never get injected. As it seems like being denied due to Thunderbird-conversations `hijacking` the content pane on some URL which seems to be the problem. I'm thereby unsure how Thunderbird-conversations works exactly in this matter.

Someone else reported that content_scripts wasn't working in #1609 - fundamentally it is a Thunderbird issue as the API is assuming the message pane is the only place messages get displayed. A reasonable assumption for Thunderbird itself, but unfortunately breaks the Conversations aspect. As mentioned there, I've filed a Thunderbird bug on it.

I'll close this out as a duplicate of that once, since it has more information there.

**Comment by Standard8** [comment] 2021-03-06 21:59
Duplicate of #1609

**Closed by Standard8** 2021-03-06 21:59 UTC
Labels: bug, future
