### ISSUE TITLE
Conversations "Error encountered while rendering" on every message

### ISSUE THREAD

**Issue by mitra42** [thunderbird-conversations/thunderbird-conversations#1682] opened 2021-07-16 05:19 UTC
* **Thunderbird version:** 91.09b1 (current beta)
* **Thunderbird Conversation version:** 3.2.26
* **Operating System:** OSX 11.4

**What did you do?** 
All messages are reporting errors rendering.   I just rebooted the machine, and I think that might have meant TB upgraded to the current version.

If I Switch off Conversations, everything works fine. 

**What actually happened?**

Error encountered while rendering.
TypeError: setting getter-only property "charset"

MessageIFrame@chrome://conversations/content/694.bundle.js line 1290 > srcScript:2288:5
ErrorBoundary@chrome://conversations/content/694.bundle.js line 1290 > srcScript:3223:5
div
li
Message@chrome://conversations/content/694.bundle.js line 1290 > srcScript:3262:5
ul
_MessageList@chrome://conversations/content/694.bundle.js line 1290 > srcScript:3631:13
ConnectFunction@chrome://conversations/content/50.bundle.js line 1290 > srcScript:244:68
_ConversationWrapper@chrome://conversations/content/694.bundle.js line 1290 > srcScript:3704:5
ConnectFunction@chrome://conversations/content/50.bundle.js line 1290 > srcScript:244:68
Provider@chrome://conversations/content/800.bundle.js line 1290 > srcScript:285:15

**Comment by Razumain** [comment] 2021-07-16 14:28
Same issue. Rolled back to version 90.0 b3.

I guess we must wait for an update of Conversations to align with version 91?

**Comment by Standard8** [comment] 2021-07-23 21:46
I thought I had just fixed this in  b57d763, however, under a bit more testing, I've found some race conditions which cause things to break quite badly. I'll see if I can take a look tomorrow and figure out a way of fixing things.

**Comment by mitra42** [comment] 2021-07-23 23:38
While you are in there, it would be worth looking at HTML messages in 3-pane view, they were not rendering properly (the scroll on the right didn't go to the bottom of the message). I was about to report it as a bug, but then it all stopped working anyway - If you can't repeat it, then I'll report next time it occurs after this one gets fixed.

**Comment by Standard8** [comment] 2021-07-24 12:21
I think I've now fixed this in a permanent way. 3.2.27 is pending approval on the add-ons site, hopefully will be released early next week.

I've also created an issue for tracking existing known issues with TB 91 beta - #1686. For possible new issues, please add them to the [discussion thread](https://github.com/thunderbird-conversations/thunderbird-conversations/discussions/1687).

@mitra42 I cannot reproduce your issue, the HTML messages are rendering and scrolling fine for me with the working version.

**Closed** 2021-07-24 12:22 UTC
