### ISSUE TITLE
New quick reply feature in 4.0.0 can't handle international characters

### ISSUE THREAD

**Issue by Razumain** [thunderbird-conversations/thunderbird-conversations#1715] opened 2021-10-06 11:37 UTC
* **Thunderbird version: 93.0b5**
* **Thunderbird Conversation version: 4.0.0**
* **Operating System: IOS 11.5.1**

**What did you do?**
Used the quick reply function in Conversation that included text in Swedish, containing the characters åäöÅÄÖ

**What did you expect to happen?**
A correct reply with the characters encoded correctly.

**What actually happened?**
Encoding failure makes the text in the reply appear with wrong international characters. Appears to be a mixup of ISO8859-1 (Latin 1) and UTF-8.

![image](https://user-images.githubusercontent.com/1091141/136195277-6cfc00d0-7556-4cd6-8e2d-d97216c34353.png)

**Comment by darthoctopus** [comment] 2021-10-08 15:38
This includes also other unicode characters; e.g. the emdash "—" gets mangled into ""

**Comment by klapanciusz** [comment] 2021-10-21 23:22
I have a quick reply issue, but (probably) not related to this one, although I also had this same problem too, and it looks like you are right, it is all non-ascii characters.

So this other problem is that the quick reply confuses my accounts. I get an email to my work email and when replying, it sometimes leaves from my personal email, and vice versa. Not always, I could not establish the pattern yet. Unfortunately, this was causing so many problems, that disabled Conversations - will now try to re-enable it with quick reply disabled, as I am not sure that it was only happening in quick reply. However, the problems stopped once I disabled Conversations, keeping all the other add-ons, so that was definitely the cause.

Win 10 64-bit, Thunderbird 91.2 EN-GB 64-bit, Conversation 4.0.1. If I figure out anything more precisely, will add further info.

**Comment by nanu-c** [comment] 2021-11-12 10:24
I have the same problem with Thunderbird version: 91.3.0 and the german umlaute äöüß

**Comment by Razumain** [comment] 2021-11-16 09:13
Are there any plans for fixing this in a near future, or is this issue permanently stuck waiting for updates in Thunderbird itself?
I would love to be able to use this feature!

**Comment by Standard8** [comment] 2021-11-21 22:54
I've think I've got a fix for this now (within Thunderbird). My previous attempt has failed because I missed something, but I think I understand why now. I'm currently running it through the tests so hopefully they'll work.

I don't think I'm going to be able to work around this in Conversations.

**Comment by klapanciusz** [comment] 2021-11-22 00:10
If it is fixed in Thunderbird, it should be fine - the question is how 
long until it is included in a release 😁

Thank you Mark.

**Comment by tim-mickelson** [comment] 2021-11-23 06:07
Could you link the issue in Thunderbird so we can follow the progress?

**Comment by vincenzoml** [comment] 2021-11-24 09:52
@klapanciusz thanks for the information; please, if you can, link the issue; also it would be good to comment here how to get a fixed version (nightly build? compile from source?).

**Comment by mbargigia** [comment] 2021-11-28 14:53
The same happens when typing in the Italian language, all accented vowels àèéìòù appear as garbage
![Schermata 2021-11-28 alle 15 52 44](https://user-images.githubusercontent.com/61627937/143773127-c2c118bd-b324-4374-8b34-87702d4bbe6c.jpg)

**Comment by Standard8** [comment] 2021-11-28 18:56
> The same happens when typing in the Italian language, all accented vowels àèéìòù appear as garbage

No need to add "me too" style comments. As the description says international character handling is broken. Adding more comments just unnecessarily spams everyone watching this.


The bug is now posted as https://bugzilla.mozilla.org/show_bug.cgi?id=1743232, it has had the first review cycle, will hopefully get approved in the next day or so, then we'll need to do uplifts to get it into the release versions, I can't currently say how exactly how long that will take, though the likely latest point for a release would be 11th Jan.

**Comment by Standard8** [comment] 2021-12-23 11:06
The fix has just been released in Thunderbird 91.4.1, please make sure you upgrade to that to get the fix.

**Closed by Standard8** 2021-12-23 11:06 UTC
Labels: thunderbird issue, bug

**Comment by klapanciusz** [comment] 2021-12-26 19:24
Thanks Mark, yes, it works fine since then :-)
