### ISSUE TITLE
PDF Drag and Drop

### ISSUE THREAD

**Issue by Rafi-50** [thunderbird-conversations/thunderbird-conversations#1809] opened 2022-03-15 15:39 UTC
* **Thunderbird version:**91.5.0 (64-bit)
* **Thunderbird Conversation version:**4.0.12
* **Operating System:** Win 10

**What did you do?**Drag and drop a PDF attachment into a directory

**What did you expect to happen?**the PDF file should be copied into the directory

**What actually happened?**a .SVG file was generated instead of the PDF file

**Comment by Standard8** [comment] 2022-03-18 09:32
Duplicate of #1722

**Closed by Standard8** 2022-03-18 09:32 UTC
