### ISSUE TITLE
How can I deactivate the compact header? I want to use the classic reader

### ISSUE THREAD

**Issue by envico801** [thunderbird-conversations/thunderbird-conversations#2070] opened 2024-01-03 20:58 UTC
* **Thunderbird version:** 115.6.0 (64-bit)
* **Thunderbird Conversation version:** 4.1.5
* **Operating System:** Windows 11

Hi, maybe this is a silly ticket, but is there a way to have the classic reader at the same time that you have the add-on active?

With the classic reader I mean the default one that thunderbird has, this one here:
![classic reader](https://github.com/thunderbird-conversations/thunderbird-conversations/assets/132226893/456f4cf2-7f44-4cbf-b583-9a2a0e6c389c)

The reader included in the add-on makes the messages look compact, like this:
![add-on reader](https://github.com/thunderbird-conversations/thunderbird-conversations/assets/132226893/c16f9836-5fa2-4fe3-9b79-e9790de7ee0c)

I know you can still use the classic reader by opening the message in a new window but I would like to avoid having to do that with every message.

Thank you ⭐

**Comment by Standard8** [comment] 2024-01-20 13:05
There's no way to do this currently, the classic view is designed around a single message being displayed. Conversations has a more compact header because of potentially displaying lots of messages.

There is an existing issue on the toolbar - #1296 so closing this as a duplicate of that.

**Closed by Standard8** 2024-01-20 13:05 UTC

**Comment by envico801** [comment] 2024-01-23 15:41
I see, thanks for the info!
