### ISSUE TITLE
I think last Thunderbird update broke this extension for me.

### ISSUE THREAD

**Issue by renan63** [thunderbird-conversations/thunderbird-conversations#1881] opened 2022-08-02 15:13 UTC
* **Thunderbird version:**
104.0b2
* **Thunderbird Conversation version:**
4.0.19
* **Operating System:**
Windows 10

**What actually happened?**
The text from messages suddenly stopped appearing.
![error](https://user-images.githubusercontent.com/49651343/182409563-6cc9875f-2e59-4cbf-b2fe-bb981527852e.JPG)
![error2](https://user-images.githubusercontent.com/49651343/182409582-23a3725a-5963-4793-ae52-1f06da54ce72.JPG)

**Comment by roaldarbol** [comment] 2022-08-03 10:11
Same issue here. Versions:

**Thunderbird version:**
104.0b2 (also on 104.0b1)
**Thunderbird Conversation version:**
4.0.19
**Operating System:**
macOS Big Sur

**Comment by cunio** [comment] 2022-08-03 10:33
The same is here.
TB: 104.0b1 and 104.0b2
Thunderbird Conversation: 4.0.19
Linux

**Comment by Standard8** [comment] 2022-08-03 10:41
Sorry, I incorrectly marked 4.0.19 as compatible with 104.x but it wasn't (otherwise it just wouldn't be enabled at all in 104). I'd already fixed it, but forgotten to publish the new version. I posted the new version yesterday, but it might take a few days for approval.

Please note, that I do not guarantee compatibility with beta versions - and I generally fix on a "when I can" basis. I'm glad people are using beta, and it is good to get reports about issues there, but please be patient when it doesn't work.

Also note that "me too" comments aren't welcome nor useful, unless they are adding extra information (and the platform doesn't really count). "me too" tends to just spam everyone and doesn't help get the issue resolved.

Duplicate of #1880

**Closed by Standard8** 2022-08-03 10:41 UTC

**Comment by roaldarbol** [comment] 2022-08-20 12:47
@Standard8 Just wanted to add that of course we're just super happy with your work on Conversations and highly appreciate it. Platforms tend to add useful information on lots of the open source projects I interact with, and if Conversations is an exception then I'm sorry to add my voice - but then please state those conditions somewhere (e.g. CONTRIBUTING.md) rather than letting us know our bit in trying to help "aren't welcome nor useful". We simply cannot know every project's policies, source code or valuable information a priori. :-)
