### ISSUE TITLE
Send button in the inline quick reply is impossible to read

### ISSUE THREAD

**Issue by Porkepix** [thunderbird-conversations/thunderbird-conversations#2088] opened 2024-03-08 10:11 UTC
* **Thunderbird version:** 115.8.1
* **Thunderbird Conversation version:** 4.1.6
* **Operating System:** ArchLinux

**What did you do?**
Click the quick reply under a thread (the one with the rectangular box to do a quick inline reply)

**What did you expect to happen?**
Everything should be correctly visible

**What actually happened?**
The send button can't be read (see screenshot below).

![Screenshot from 2024-03-08 11-09-38](https://github.com/thunderbird-conversations/thunderbird-conversations/assets/709500/f1e216ae-a9be-45ff-a395-d28a564b3cf5)

**Comment by Standard8** [comment] 2024-03-10 09:36
Duplicate of #1933

**Closed** 2024-03-10 09:36 UTC
