### ISSUE TITLE
Interacting with Calendar Invites is broken

### ISSUE THREAD

**Issue by ryanleesipes** [thunderbird-conversations/thunderbird-conversations#1810] opened 2022-03-16 18:52 UTC
**Thunderbird version:** 99.0b1 (Beta)
**Thunderbird Conversation version:** 4.0.12
**Operating System:** MacOS Monterey (12.3)

**What did you do?**
When accepting, declining, marking tenative, or clicking on update for an event nothing happens after clicking this.

When I went to classic reader it worked.

**What did you expect to happen?**

Expected to choose a calendar and have the event show up there.

**What actually happened?**

Nothing, it acted as though I didn't interact with the invite.

<img width="1301" alt="Screen Shot 2022-03-16 at 12 06 24 PM" src="https://user-images.githubusercontent.com/2141621/158657955-9d1526cc-0ccd-40a2-a2c6-a4d5d09debe3.png">

^ Clicking the above does nothing

**Note:** This may be a Thunderbird issue, but it's weird that I have gotten it to work in the classic reader.

**Comment by Standard8** [comment] 2022-03-18 09:15
Accept/decline/tentative seem to be working for me, though [testing those is difficult](https://bugzilla.mozilla.org/show_bug.cgi?id=1760272). Checking the console for errors might help.

Update is broken, but even if I fix that nothing really happens which is the same as per Thunderbird - the update button disappears briefly and then comes back again. Maybe [bug 1751370](https://bugzilla.mozilla.org/show_bug.cgi?id=1751370)?

**Comment by Standard8** [comment] 2022-03-18 09:32
I just pushed 77a5eb129cef998a3fcdc5789a949bc30ab286aa which will fix the update button, it also fixes/adds the "details" button onto the "This message has already been processed" notification, as well as potentially adding some other buttons that I've never seen.

I don't think that would fix issues with accept/decline etc.

**Comment by Standard8** [comment] 2022-05-07 08:02
@ryanleesipes Is this any better now with 4.0.14?

**Comment by ryanleesipes** [comment] 2022-05-07 15:34
It's strange. It was at first, but now the behavior is back. 🤷‍♂️

**Comment by oreineke** [comment] 2022-05-12 12:28
I also see this behavior: A click on "Decline", "Tentative", or "Accept" has no visible effect.

However, once I select another mail, then come back to the original mail with the invitation, then clicking on one of the three invite reaction buttons works as intended.

Here is the console output generated when clicking on "Accept" the first time (and nothing happens):

![accept error](https://user-images.githubusercontent.com/2112060/168074035-b7a53eb0-1523-489c-b864-86525a2a8484.PNG)

**Comment by Standard8** [comment] 2022-06-01 08:11
A new version has just been released - 4.0.17 - which may help some of this, I'm not totally sure, but it is probably worth checking out.

**Comment by Standard8** [comment] 2023-10-28 12:05
My hope is that this is now fixed in Conversations 4.1.5 and later on Thunderbird 115.x. Due to the changes in Thunderbird, I had to do extensive reworking of the calendar support. As a result, I think I found a few cases I'd missed previously, and I'm fairly sure there's more complete support in there now.

I'm going to close this out, but please feel free to file a new issue if it is still happening.

**Closed by Standard8** 2023-10-28 12:05 UTC
Labels: investigate
