### ISSUE TITLE
Dark mode in the message window

### ISSUE THREAD

**Issue by ReiNarumiya** [thunderbird-conversations/thunderbird-conversations#1887] opened 2022-08-18 09:48 UTC
Dark Mode in "Thunderbird conversations" doesn't work in the message window (email body). 
I am wondering if you have any plans to deal with this problem? 
(I know "Darko" can do it, but this add-on does not work when you use it with "Thunderbird conversations" turned on.)
I'm sorry if this has already been posted because I could not find the thread about it.

**Comment by Standard8** [comment] 2022-08-27 10:46
Duplicate of #1611

**Closed by Standard8** 2022-08-27 10:46 UTC
