### ISSUE TITLE
[Enhancement] Adding dark mode to the conversations 

### ISSUE THREAD

**Issue by ldm021** [thunderbird-conversations/thunderbird-conversations#2150] opened 2024-09-30 14:49 UTC
![image](https://github.com/user-attachments/assets/7e5d1418-b47f-4366-a9c4-7400d8a18c11)

Many thanks for the great add-on! Would it be possible to add a dark mode also to the messages when shown as conversations?
This would be greatly appreciated, as I can see the usefulness of the add-on, yet not having dark mode in there defeats the purporse of a dark mode entirely, which I my case I prefer to use. Many thanks in advance

**Comment by Standard8** [comment] 2024-09-30 16:17
Duplicate of #1611

**Closed** 2024-09-30 16:17 UTC
