### ISSUE TITLE
BetterUnsubscribe button not available in custom header

### ISSUE THREAD

**Issue by brad-za** [thunderbird-conversations/thunderbird-conversations#2161] opened 2024-11-08 13:43 UTC
Thunderbird conversations does not show the button [BetterUnsubscribe](https://github.com/LucBennett/BetterUnsubscribe) creates at the top of an email conversation

* **Thunderbird version:** 128.4.1esr
* **Thunderbird Conversation version:** 4.2.3
* **Operating System:** Ubuntu GNOME

**What did you do?** When installing the extension the custom top view does not include buttons created by other extensions

**What did you expect to happen?** the unsubscribe button should show in the custom header or there should be an option to disable the custom header and include the new functionality in buttons in the stock header

**Comment by Standard8** [comment] 2024-11-09 09:19
> **What did you expect to happen?** the unsubscribe button should show in the custom header or there should be an option to disable the custom header and include the new functionality in buttons in the stock header

Disabling the custom header isn't possible, since Conversation's headers are designed to work with multiple messages, which is not possible with the single message custom header.

Unfortunately this is a hard problem to solve, because of the way the integration works. There is already #1665 covering this, so I'm closing this as a duplicate of that issue.

**Closed by Standard8** 2024-11-09 09:19 UTC
