### ISSUE TITLE
CTRL+Enter no longer sends a message

### ISSUE THREAD

**Issue by kidsil** [thunderbird-conversations/thunderbird-conversations#2039] opened 2023-10-26 21:07 UTC
Without Thunderbird conversation addon, I was able to send a message using CTRL+ENTER.
After installing the addon, I'm no longer able to trigger the sending of a message using said shortcut.

**Comment by Standard8** [comment] 2023-10-27 07:13
Conversations' doesn't affect the separate compose window, so if you're using that you should still be able to use ctrl-enter.

If you're using the in-line quick reply, then this is a duplicate of #1740

**Comment by Standard8** [comment] 2023-10-28 12:00
Duplicate of #1740

**Closed by Standard8** 2023-10-28 12:00 UTC
