### ISSUE TITLE
Some Attachments are not seen (Especially in PGP Encrypted mails)

### ISSUE THREAD

**Issue by manicmarvin** [thunderbird-conversations/thunderbird-conversations#1549] opened 2020-11-06 07:55 UTC
* **Thunderbird version: 78.4.0**
* **Thunderbird Conversation version: **
* **Operating System: macOS/OSX**

Attachments that are PDFs or Images are usually visible in TBConversations. But non-mainstream files with differnt extensions (such as .odts's, .asc's, .ods, .tar.gz's, etc...) tend to be invisible and I have to open the email in classic reader to view the attachments.  I can't confirm if this is consistent behaviour with non-encrypted mails (it sometiems works for more extensions) but it is definitely true for all encrypted mails.

This is becoming a big pain especially for the non-techy people I have recommended the plugin to. 

I have tried with `I love attachments` on and off with `Show All Body parts` on as well as off. 

Is this an easy fix? Or is this a big pain?

**Comment by Standard8** [comment] 2020-11-08 20:24
Duplicate of #1524

**Closed by Standard8** 2020-11-08 20:24 UTC

**Comment by daurnimator** [comment] 2022-07-21 12:50
This still exists for me in 4.0.19
