### ISSUE TITLE
single quote shows as â€™

### ISSUE THREAD

**Issue by ChrisChris115** [thunderbird-conversations/thunderbird-conversations#1538] opened 2020-10-04 02:06 UTC
TBird 82.0b2
Conversations 3.1.22
MacOS 10.15.7

single quotes used for apostrophes show up as â€™ instead of '
If I turn off conversations things are fine.
![with convo](https://user-images.githubusercontent.com/72326453/95005291-82fb8400-05ab-11eb-8bd0-ba9e6aa2f67c.png)
![without convo](https://user-images.githubusercontent.com/72326453/95005292-842cb100-05ab-11eb-8207-af04f4512b02.png)

**Comment by Standard8** [comment] 2020-10-04 08:24
Duplicate of #1528

**Closed by Standard8** 2020-10-04 08:24 UTC
