### ISSUE TITLE
Only first line of Email shown in conversations view, Emails cannot be toggled to full view.

### ISSUE THREAD

**Issue by ts-mz** [thunderbird-conversations/thunderbird-conversations#2153] opened 2024-10-11 13:21 UTC
* **Thunderbird version:**
128.3.0esr (32-Bit)

* **Thunderbird Conversation version:**
4.2.2

* **Operating System:**
Windows 11 Fully Updated

**What did you do?**
Open the last message of a thread in list view. 

**What did you expect to happen?**
Show the thread and the entire last email.

**What actually happened?**
The thread is shown in the message pane, but neither is the last message shown in full, only literally half of the first line of text is visible, nor is it possible to toggle the full view for the last or any other email in the thread. When clicking on any email in the thread, the messages will open only to show as much as the last message did upon opening the thread: show only half of the first line of text. The email inside the small open box is scrollable, but only one line of text will be visible at the same time.

![thunderbird-conversations-screenshot](https://github.com/user-attachments/assets/ccb8165e-a46e-4e14-b6e9-52d7b52d36f3)

**Comment by Standard8** [comment] 2024-10-12 08:51
Duplicate of #2121

**Closed by Standard8** 2024-10-12 08:51 UTC
