### ISSUE TITLE
With thunderbird conversations plugin enabled, some messages are reported as "deleted", only header is available

### ISSUE THREAD

**Issue by ICannotRemember** [thunderbird-conversations/thunderbird-conversations#1751] opened 2021-11-12 08:11 UTC
* **Thunderbird version: 91.3.0, 32bit
* **Thunderbird Conversation version: 4.05
* **Operating System: Win10 Pro, 21H1

**What did you do?**
Tried to see content of a message, both by just clicking on the message and by opening it in new tab

**What did you expect to happen?**
See the message

**What actually happened?**
When just clicking on the message, no body was displayed.
When opening it in new tab, I got this message (translated from my local language)
We are sorry, but this conversation can't be displayed, because it's messages were moved or deleted.

Doesn't happen to most messages, only some of them - most noticably daily google calendar messages are affected.
As soon as I disable this plugin, messages are displayed in full, no problem. As soon as plugin is enabled, you can only see headers.
Also, it depends on what *folder* the message is in. Same message working in one folder will not be displayed in another.
Example: Message in important folder is "empty", but when I move to inbox folder, message is there in full. That doesn't mean *all* messages in that folder are "empty", but it seems it's very likely to happen to some folders and not to others.
If some messages are working in folder A, and you click on another, "empty" message in folder A, then body of the previous message is still displayed.

If you want screenshots, logs, etc, just tell me what to do.

**Comment by Standard8** [comment] 2021-11-12 08:25
Is it possible that the folders where this is broken have non-ascii characters? If so, this is a duplicate of #1746 which is an issue caused by Thunderbird itself.

I've currently got fixes going into Thunderbird to resolve that in one of the next releases of Thunderbird. Unfortunately Conversations is relying on something that's broken in Thunderbird and the only way to fix it is to fix Thunderbird.

**Comment by ICannotRemember** [comment] 2021-11-12 08:38
Definitely non-english characters in folder names:
problem folder: imap://accountname@imap.gmail.com/Kalend%C3%A1%C5%99
working folder: imap://accountname@imap.gmail.com/INBOX
I have seen issue 1746, just didn't know this is another way this issue shows itself.

**Comment by Standard8** [comment] 2021-11-12 08:39
Duplicate of #1746

**Closed by Standard8** 2021-11-12 08:39 UTC
