### ISSUE TITLE
Ctrl + F hot key to Find Text in Current Message doesn't work in Thunderbird 78.5.0 (32 bit) on WIN10

### ISSUE THREAD

**Issue by tomekson** [thunderbird-conversations/thunderbird-conversations#1563] opened 2020-11-25 11:45 UTC
* **Thunderbird 78.5.0 (32 bit)**
* **Thunderbird Conversation version: 3.2.6**
* **Operating System: Windows 10, 64bit**

**What did you do?**
After Conversation add-on instalation and restarting Thunderbird I pressed Ctrl + F hot key to get input field for searching within messages. No other add-on is installed.

**What did you expect to happen?**
I expected an input field to appear to find text in current message.

**What actually happened?**
No input field appeared, so I am unable to search for text within a message.
Once Thunderbird Conversation add-on is uninstalled, Ctrl + F works again - the input field appears as usual and I can search within message for my text.

**Comment by Standard8** [comment] 2020-11-25 12:10
Thank you for filing - this is already known in #241. Unfortunately it is an issue with Thunderbird's architecture that is difficult to solve.

**Comment by Standard8** [comment] 2020-11-25 12:10
Duplicate of #241

**Closed by Standard8** 2020-11-25 12:10 UTC
