### ISSUE TITLE
Reverse Order of Thread

### ISSUE THREAD

**Issue by OniJoshin** [thunderbird-conversations/thunderbird-conversations#1561] opened 2020-11-20 16:52 UTC
Would it be possible to add a feature / setting to reverse the order of threaded emails so the latest one is at the top and automatically open with the previous emails listed below.

**Comment by Standard8** [comment] 2020-11-20 16:57
Duplicate of #1440

Please see my recent comments there.

**Comment by Standard8** [comment] 2020-11-20 16:57
Duplicate of #1440

**Closed by Standard8** 2020-11-20 16:57 UTC
