### ISSUE TITLE
Message from another thread shown in an email thread

### ISSUE THREAD

**Issue by Porkepix** [thunderbird-conversations/thunderbird-conversations#2091] opened 2024-03-20 15:22 UTC
* **Thunderbird version:** 115.8.1
* **Thunderbird Conversation version:** 4.1.6
* **Operating System:** Linux

**What did you do?**
Shows a thread content by having it selected

**What did you expect to happen?**
Nothing special, just see the thread and nothing else.

**What actually happened?**
A message from another thread was shown and visible at the end of the thread, not linked in any way to the whole thread.
I unfortunately can't provide a meaningful screenshot as I tend to avoid screenshoting emails and pixellating everything would basically render the screenshot useless.

To try to sum it up better with a simplified drawing of what I saw:

List of messages view:
```
Thread A
Thread B <-- this thread is the current selected one
Thread C 
```

Message view:
```
Thread B, message 1
Thread B, message 2
Thread B, message 3
Thread B, message 4
Thread B, message 5
Thread A message X (last message recently received from thread A).
```

Note that after selecting another thread and going back to thread B, the message that shouldn't be here was gone.

EDIT: This just happened again after I un-marked as junk an email without selecting it; it was treated as received again by TB and appeared at the end of the currently selected thread while not belonging there.

**Comment by Standard8** [comment] 2024-03-26 09:04
Thank you for the report. The piece about marking as not Junk is interesting. I've just been trying to reproduce it and unfortunately I've not yet been able to.

What are your Junk settings set to? Do they keep the mail in the same folder, or do they move it to a different folder?

If you're moving to a different folder, how did you mark it as not junk?

Also, is there anything about the threads that are potentially highly related? For example, the same contacts in both threads, or similar subjects?

**Comment by Standard8** [comment] 2024-03-27 13:07
Just a thought, is it possible that you've selected Thread A prior to reading Thread B, and then do the marking as not junk on the Thread A?

I see the possibility for a race condition in the Conversations code, but I think it'd be unlikely to manifest on the whole. I might try patching it though and see if that helps.

**Comment by Standard8** [comment] 2024-04-12 09:51
Conversations 4.1.7 is out now, so it might be worth checking if you're on that, and then seeing how it goes for a few days.

**Comment by iamkaant** [comment] 2024-07-17 23:57
I have the same issue when unrelated threads are mixed. If I reply to a message within this "mixed" thread, the reply subject will differ from the thread subject, but the sent message will go into the same thread. Please LMK if I can provide any info to investigate.

**Comment by Standard8** [comment] 2024-10-12 09:01
> I have the same issue when unrelated threads are mixed. If I reply to a message within this "mixed" thread, the reply subject will differ from the thread subject, but the sent message will go into the same thread. Please LMK if I can provide any info to investigate.

I think this is most likely an issue with Thunderbird's association of threads. For threads, Conversations uses information from Thunderbird's global database. Hence if the threads are being mixed, it is most likely a Thunderbird issue.

If the messages are mixed in the thread pane, that is definitely Thunderbird's issue.

If the messages are mixed in the message pane, then you should be able to hover over one of the authors and select to show recent conversations. If the messages are mixed up there as well, then it is Thunderbird's issue.



I'm going to close this out, since I updated Conversations and not had any more reports of the original issue, so hopefully that fixed it.

**Closed by Standard8** 2024-10-12 09:01 UTC

**Comment by Porkepix** [comment] 2026-08-05 13:27
@Standard8 This happened again, curiously on an email I caught in spams, marked as not junk and then when I got back to the Inbox, it was added to another completely unrelated email and recipients, with both coming from different mailing lists.

Same question as above, could we reopen here? should I open another similar issue?
