### ISSUE TITLE
Once clicked, the answer or forward buttons in a thread becomes almost of the same color as the background

### ISSUE THREAD

**Issue by Porkepix** [thunderbird-conversations/thunderbird-conversations#2087] opened 2024-03-08 10:09 UTC
* **Thunderbird version:** 115.8.1
* **Thunderbird Conversation version:** 4.1.6
* **Operating System:** ArchLinux

**What did you do?**
Click a reply or forward button in a thread

**What did you expect to happen?**
Those buttons once clicked should stay visible

**What actually happened?**
After click they becomes almost of the same color as the background and therefore invisible. Only the last clicked button stays like that, ie. once another one button is clicked, it becomes visible again.

See these screenshots for the two places where it happens, and to see how it looks like.

Top of the message
![Screenshot from 2024-03-08 11-00-40](https://github.com/thunderbird-conversations/thunderbird-conversations/assets/709500/d0e658a1-c4d1-4522-ba51-7941eaa991ad)

Bottom of the message
![Screenshot from 2024-03-08 11-00-49](https://github.com/thunderbird-conversations/thunderbird-conversations/assets/709500/8b145bc0-da74-409c-b5d4-8c6bcf3ccca3)

Same top of the message after clicking the reply button
![Screenshot from 2024-03-08 11-01-12](https://github.com/thunderbird-conversations/thunderbird-conversations/assets/709500/e7fcc4c2-5f6c-4c18-a12c-ba3c0bf87f55)

**Comment by Standard8** [comment] 2024-03-10 09:34
Duplicate of #1611

**Comment by Standard8** [comment] 2024-03-10 09:35
This looks like you're using dark mode which isn't fully supported currently. See #1611

**Closed by Standard8** 2024-03-10 09:35 UTC
