### ISSUE TITLE
"between" column cannot be removed again

### ISSUE THREAD

**Issue by Sick-Andrew** [thunderbird-conversations/thunderbird-conversations#1772] opened 2022-01-04 11:01 UTC
Thunderbird version: 91 / Betterbird 91.4.1-bb23 (64-Bit)
Thunderbird Conversation version: 4.0.8
Operating System: Win 10 Pro

When turning on the column "between" in the messages overview (the one that shows between who a conversatation is taking place) I cannot disable it again. I can remove the tick and the column dissapears but on a restart of TB the column is back there on first position. Issue appears in both - TB and BB.

**Comment by Standard8** [comment] 2022-01-04 12:47
Duplicate of #1426 

Some of the comments there may or may not help.

Please note that Betterbird support is only on an if it works basis. We only support Thunderbird, if it happens to work there, that's fine, but I'm not going to do specific work to support it.

**Closed by Standard8** 2022-01-04 12:47 UTC
