### ISSUE TITLE
When reply last signature from identities list is used insted of default

### ISSUE THREAD

**Issue by OsadaP** [thunderbird-conversations/thunderbird-conversations#1750] opened 2021-11-09 10:58 UTC
* **Thunderbird version: 91.3.0**
* **Thunderbird Conversation version: 4.0.5**
* **Operating System: Windows 10 21H1 (19043.1288)**

**What did you do?**
I have configured four identities using HTML files:
![Zrzut ekranu 2021-11-09 115252](https://user-images.githubusercontent.com/86242069/140911308-515bf655-a54d-4c5c-a893-f4fa25a9f071.png)
Let's name it:
* Default ID
* ID2
* ID3
* ID4 (last on the list)

When I click to response for mail that have only one recipient (write only for one sender) then in mail window there is attached last signature (ID4).
![Zrzut ekranu 2021-11-09 114941](https://user-images.githubusercontent.com/86242069/140910896-0ca77c10-b452-492d-9843-bf5fb788a5dd.png)

When email was send for group of recipients then clicking "reply all" correctly attaches **Default ID**.
![Zrzut ekranu 2021-11-09 115645](https://user-images.githubusercontent.com/86242069/140912110-6a2feb1a-d5ca-4344-92f8-f996a79c74e1.png)

**Comment by Standard8** [comment] 2021-11-12 08:36
When the signature is wrong, has Thunderbird also select the wrong "From" address displayed at the top of the email you are composing?

If the from address is also wrong, could it be that Thunderbird is using the address that the mail was sent to?

Is the mail in local folders?

**Comment by OsadaP** [comment] 2021-11-15 13:31
Ad. 3 question: I do not use local folders.
My exact configuration is:
**1st** Default: Academic mail (agh.edu.pl - roundcube webmail) --- _me1_
- ID1 (signature 1)
- ID2 (S2)
- ID3 (S3)
- ID4 (S4)

**2nd** Second account: Gmail --- _me2_
- 2_ID1 (2_S1)
- 2_ID2 (2_S2)
- 2_ID3 (2_S3)
- 2_ID4 (2_S4)

Ad. 1 question: No. When signature is form 1st account, then mail in field _from_ is also from 1st account (it this aspect it behaves properly).

Ad. 2 question: Yes. As shows two pictures below:
- If we responds to our mails (on default account) TB Conversations uses proper identity (and proper singnature, that is connected with it).
- If we responds to our mails (on second account) TB Conversations uses identity that mail was send from. And for me it's bad behaviour. Because when I'm in 2nd account I want to send mails by 2nd account identity by default.

![7-8 wątek pomiędzy dwoma kątami](https://user-images.githubusercontent.com/86242069/141784652-c1624280-7b55-49e2-8a42-125bd8ed2787.jpg)

As second picture sumarises: 
- Responses to other persons are always with identity from 1st account. 
- And responses to ourselves are using mails that was send from. Which for me should use mails of account we using when reading this thread.
![7-8 wątek pomiędzy dwoma kątami 9 10](https://user-images.githubusercontent.com/86242069/141787163-dea8065e-4009-4e26-ab08-5628a29417e3.jpg)

In below picture example 4) shows that when mail was sent to group of specific mails from field:
-  _To_ then reply all gives ID4,
-  _Cc_ then reply all gives ID1 (properly in case of 1st account).

Example 6) shows that reply to list uses proper identity (2nd acc ==> 2_ID1).
![3-6](https://user-images.githubusercontent.com/86242069/141789526-5f24ef52-a1cd-457c-abc4-6a651f4fa308.jpg)

**Comment by Standard8** [comment] 2021-11-27 09:36
Conversations version 4.0.7 has just been released with some additional fixes for identity selection, please can you try that and see if it is any better.

**Comment by OsadaP** [comment] 2021-11-30 15:39
* **Thunderbird version: 91.3.2**
* **Thunderbird Conversation version: 4.0.7**
* **Operating System: Windows 10 21H2 (19044.1387)**

The problem still exists when replying to single person (a last ID from the same account is used).
Replying to: ourselves; many addresses and to mailing list retains appropriate personality.

There is another issue that in my second account (configured mail): when replying to a single mail (not to myself but to other person) the last ID is used and mail composing is in text mode (not HTML). In the same situation in classic view everything the HTML and default ID is used.

PS
I don't think that it is connected, but under above mentioned software versions, Thunderbird crashes when entering Thunderbird properties.

**Comment by Standard8** [comment] 2021-12-02 13:53
Hi, I can't reproduce your additional issue.

In my main account I have two identities and if I switch emails between ones which were addressed to different identities, or via bcc then they all work fine.

Are you sure that when it exists it is not using the default identity for the account? If it cannot identify which email address it was sent to (e.g. because it was BCC or does not match one of your identities), it will fallback to the default identity for that account.

**Comment by OsadaP** [comment] 2021-12-02 20:46
* **Thunderbird version: 91.3.0 (RPM repository)**
* **Thunderbird Conversation version: 4.0.7**
* **Operating System: fedora 35**

Are you sure that **when it exists** it is not using the default identity for the account?

**when it exists**
Did you ment that when some account has additional identities?

In my case TB Conv sometimes uses default id and sometimes other id:

- @agh.edu.pl -- reply all --> last id
![AGH reply all - last id](https://user-images.githubusercontent.com/86242069/144498841-f020ea84-6ceb-46a6-9f53-75a01a99145e.png)

- @agh.edu.pl -- reply my response --> default id
![AGH reply me - id1](https://user-images.githubusercontent.com/86242069/144498847-6fcfae32-d575-454a-9e9b-583e241da3fb.png)

- @gmail.com -- reply mailing list --> default id
![Gmail reply list - id1](https://user-images.githubusercontent.com/86242069/144498850-70f96573-b5d9-4820-b34a-8aab380fbb20.png)

- @protonmail.com (Proton Bridge) -- reply mailing list --> last id
![Protonmail reply list - last id](https://user-images.githubusercontent.com/86242069/144498851-0f270330-cc15-4540-844f-c0db264fa274.png)

An setting "Reply from this identity when delivery headers math:" seems not to change above examples.
![Zrzut ekranu z 2021-12-02 20-55-25](https://user-images.githubusercontent.com/86242069/144498894-cb1f2b64-beeb-4231-9e03-307e6b940a60.png)
![Zrzut ekranu z 2021-12-02 20-55-57](https://user-images.githubusercontent.com/86242069/144498896-763a52e6-ffd3-454c-abf2-78f5bb4a0321.png)

**Comment by OsadaP** [comment] 2021-12-02 20:50
PS
An _additional issue_ does not occurs on fedora 35, but also exists on Windows 11 21H2 22000.348.

**Comment by VictorCampillo** [comment] 2022-01-28 14:00
I have the same issue.

A few days ago I got the update of Thunderbird 91.5.0 on Xubuntu 20.04.03, and since then, the conversations addon always pick up the last identity of each profile, instead of the default identity.

If I disable the Conversations Addon, Thunderbirds pick up the default identity correctly.

My system is the next:

    Thunderbird version: 91.5.0 (64Bits)
    Thunderbird Conversation version: 4.0.9
    Operating System: Xubuntu 20.04.03

**Comment by Standard8** [comment] 2022-06-11 09:30
I think I've finally worked this out - the issue being that the identities all have the same email address. That's not a case I've come across before and wasn't explicitly state, so I hadn't thought about it.

In any case, I've got a fix for it which will go out in the next release which will probably be within a week or so.

**Closed** 2022-06-11 09:32 UTC
Labels: investigate
