### ISSUE TITLE
Invitation reply missing "Do not send a response"

### ISSUE THREAD

**Issue by donjan** [thunderbird-conversations/thunderbird-conversations#2146] opened 2024-09-18 09:31 UTC
Thunderbird 115.15.0 (64-bit)
Thunderbird Conversations 4.1.7
Ubuntu 24.04.1 LTS

**What did you do?**
Receive an event invitation.

**What did you expect to happen?**
Accept the invitation without sending an explicit response and spamming the host.
![Screenshot from 2024-09-18 11-24-35](https://github.com/user-attachments/assets/d292a503-cb26-428c-befc-548d3decdf50)

**What actually happened?**
No option to reply with "Do not send a response". Have to open in classic viewer and accept there.
![Screenshot from 2024-09-18 11-24-24](https://github.com/user-attachments/assets/b62b30b1-3969-46f4-b282-cf471ee41241)

**Comment by Standard8** [comment] 2024-10-12 09:13
Overall this needs a better UI, and Thunderbird has been working on something, though I don't know if we'd be able to re-use it.

Therefore I'm going to say this is a duplicate of #2074

**Closed by Standard8** 2024-10-12 09:13 UTC
